export default {
  "title": "Настоящее простое время (Present Simple)",
  "questions": [
    {"question":"«He ___ to school every day.» Выбери правильную форму глагола.","variants":["goed","go","goes","goesing"],"answer":["goes"]},
    {"question":"«She ___ to school every day.» Выбери правильную форму глагола.","variants":["go","goes","goed","goesing"],"answer":["goes"]},
    {"question":"«They ___ to school every day.» Выбери правильную форму глагола.","variants":["goes","going","goed","go"],"answer":["go"]},
    {"question":"«We ___ to school every day.» Выбери правильную форму глагола.","variants":["goed","go","going","goes"],"answer":["go"]},
    {"question":"«I ___ to school every day.» Выбери правильную форму глагола.","variants":["goed","goes","go","going"],"answer":["go"]},
    {"question":"«You ___ to school every day.» Выбери правильную форму глагола.","variants":["go","goed","going","goes"],"answer":["go"]},
    {"question":"«He ___ football every day.» Выбери правильную форму глагола.","variants":["played","playsing","plays","play"],"answer":["plays"]},
    {"question":"«She ___ football every day.» Выбери правильную форму глагола.","variants":["plays","playsing","played","play"],"answer":["plays"]},
    {"question":"«They ___ football every day.» Выбери правильную форму глагола.","variants":["playing","played","plays","play"],"answer":["play"]},
    {"question":"«We ___ football every day.» Выбери правильную форму глагола.","variants":["plays","playing","played","play"],"answer":["play"]},
    {"question":"«I ___ football every day.» Выбери правильную форму глагола.","variants":["play","played","playing","plays"],"answer":["play"]},
    {"question":"«You ___ football every day.» Выбери правильную форму глагола.","variants":["playing","play","played","plays"],"answer":["play"]},
    {"question":"«He ___ apples every day.» Выбери правильную форму глагола.","variants":["likeed","like","likes","likesing"],"answer":["likes"]},
    {"question":"«She ___ apples every day.» Выбери правильную форму глагола.","variants":["likeed","likesing","like","likes"],"answer":["likes"]},
    {"question":"«They ___ apples every day.» Выбери правильную форму глагола.","variants":["likes","likeed","like","likeing"],"answer":["like"]},
    {"question":"«We ___ apples every day.» Выбери правильную форму глагола.","variants":["likeing","like","likes","likeed"],"answer":["like"]},
    {"question":"«I ___ apples every day.» Выбери правильную форму глагола.","variants":["like","likeing","likes","likeed"],"answer":["like"]},
    {"question":"«You ___ apples every day.» Выбери правильную форму глагола.","variants":["likeing","likeed","like","likes"],"answer":["like"]},
    {"question":"«He ___ books every day.» Выбери правильную форму глагола.","variants":["readsing","reads","read","readed"],"answer":["reads"]},
    {"question":"«She ___ books every day.» Выбери правильную форму глагола.","variants":["readsing","reads","readed","read"],"answer":["reads"]},
    {"question":"«They ___ books every day.» Выбери правильную форму глагола.","variants":["read","readed","reads","reading"],"answer":["read"]},
    {"question":"«We ___ books every day.» Выбери правильную форму глагола.","variants":["read","reads","readed","reading"],"answer":["read"]},
    {"question":"«I ___ books every day.» Выбери правильную форму глагола.","variants":["reads","read","readed","reading"],"answer":["read"]},
    {"question":"«You ___ books every day.» Выбери правильную форму глагола.","variants":["reading","read","reads","readed"],"answer":["read"]},
    {"question":"«He ___ my mum every day.» Выбери правильную форму глагола.","variants":["helps","helpsing","help","helped"],"answer":["helps"]},
    {"question":"«She ___ my mum every day.» Выбери правильную форму глагола.","variants":["helps","helpsing","help","helped"],"answer":["helps"]},
    {"question":"«They ___ my mum every day.» Выбери правильную форму глагола.","variants":["helping","help","helped","helps"],"answer":["help"]},
    {"question":"«We ___ my mum every day.» Выбери правильную форму глагола.","variants":["helps","helping","helped","help"],"answer":["help"]},
    {"question":"«I ___ my mum every day.» Выбери правильную форму глагола.","variants":["help","helping","helps","helped"],"answer":["help"]},
    {"question":"«You ___ my mum every day.» Выбери правильную форму глагола.","variants":["helping","help","helped","helps"],"answer":["help"]},
    {"question":"«He ___ bread every day.» Выбери правильную форму глагола.","variants":["eated","eats","eatsing","eat"],"answer":["eats"]},
    {"question":"«She ___ bread every day.» Выбери правильную форму глагола.","variants":["eated","eats","eatsing","eat"],"answer":["eats"]},
    {"question":"«They ___ bread every day.» Выбери правильную форму глагола.","variants":["eat","eating","eated","eats"],"answer":["eat"]},
    {"question":"«We ___ bread every day.» Выбери правильную форму глагола.","variants":["eat","eating","eated","eats"],"answer":["eat"]},
    {"question":"«I ___ bread every day.» Выбери правильную форму глагола.","variants":["eating","eats","eat","eated"],"answer":["eat"]},
    {"question":"«You ___ bread every day.» Выбери правильную форму глагола.","variants":["eats","eat","eating","eated"],"answer":["eat"]},
    {"question":"«He ___ fast every day.» Выбери правильную форму глагола.","variants":["run","runed","runs","runsing"],"answer":["runs"]},
    {"question":"«She ___ fast every day.» Выбери правильную форму глагола.","variants":["run","runs","runed","runsing"],"answer":["runs"]},
    {"question":"«They ___ fast every day.» Выбери правильную форму глагола.","variants":["runs","run","runing","runed"],"answer":["run"]},
    {"question":"«We ___ fast every day.» Выбери правильную форму глагола.","variants":["runs","runing","runed","run"],"answer":["run"]},
    {"question":"«I ___ fast every day.» Выбери правильную форму глагола.","variants":["runing","runs","run","runed"],"answer":["run"]},
    {"question":"«You ___ fast every day.» Выбери правильную форму глагола.","variants":["runed","runing","run","runs"],"answer":["run"]},
    {"question":"«He ___ in the room every day.» Выбери правильную форму глагола.","variants":["sleeps","sleepsing","sleep","sleeped"],"answer":["sleeps"]},
    {"question":"«She ___ in the room every day.» Выбери правильную форму глагола.","variants":["sleeps","sleepsing","sleep","sleeped"],"answer":["sleeps"]},
    {"question":"«They ___ in the room every day.» Выбери правильную форму глагола.","variants":["sleeped","sleeping","sleeps","sleep"],"answer":["sleep"]},
    {"question":"«We ___ in the room every day.» Выбери правильную форму глагола.","variants":["sleeping","sleep","sleeps","sleeped"],"answer":["sleep"]},
    {"question":"«I ___ in the room every day.» Выбери правильную форму глагола.","variants":["sleeps","sleeping","sleep","sleeped"],"answer":["sleep"]},
    {"question":"«You ___ in the room every day.» Выбери правильную форму глагола.","variants":["sleep","sleeped","sleeps","sleeping"],"answer":["sleep"]},
    {"question":"«He ___ in the sea every day.» Выбери правильную форму глагола.","variants":["swims","swim","swimsing","swimed"],"answer":["swims"]},
    {"question":"«She ___ in the sea every day.» Выбери правильную форму глагола.","variants":["swim","swimsing","swims","swimed"],"answer":["swims"]},
    {"question":"«They ___ in the sea every day.» Выбери правильную форму глагола.","variants":["swims","swim","swiming","swimed"],"answer":["swim"]},
    {"question":"«We ___ in the sea every day.» Выбери правильную форму глагола.","variants":["swimed","swim","swims","swiming"],"answer":["swim"]},
    {"question":"«I ___ in the sea every day.» Выбери правильную форму глагола.","variants":["swims","swimed","swim","swiming"],"answer":["swim"]},
    {"question":"«You ___ in the sea every day.» Выбери правильную форму глагола.","variants":["swiming","swimed","swims","swim"],"answer":["swim"]},
    {"question":"«He ___ high every day.» Выбери правильную форму глагола.","variants":["jumps","jumped","jump","jumpsing"],"answer":["jumps"]},
    {"question":"«She ___ high every day.» Выбери правильную форму глагола.","variants":["jumps","jump","jumpsing","jumped"],"answer":["jumps"]},
    {"question":"«They ___ high every day.» Выбери правильную форму глагола.","variants":["jumping","jumps","jump","jumped"],"answer":["jump"]},
    {"question":"«We ___ high every day.» Выбери правильную форму глагола.","variants":["jumps","jumping","jumped","jump"],"answer":["jump"]},
    {"question":"«I ___ high every day.» Выбери правильную форму глагола.","variants":["jumps","jumping","jump","jumped"],"answer":["jump"]},
    {"question":"«You ___ high every day.» Выбери правильную форму глагола.","variants":["jumps","jump","jumped","jumping"],"answer":["jump"]},
    {"question":"«He ___ songs every day.» Выбери правильную форму глагола.","variants":["singed","sings","singsing","sing"],"answer":["sings"]},
    {"question":"«She ___ songs every day.» Выбери правильную форму глагола.","variants":["singsing","sing","sings","singed"],"answer":["sings"]},
    {"question":"«They ___ songs every day.» Выбери правильную форму глагола.","variants":["sings","sing","singed","singing"],"answer":["sing"]},
    {"question":"«We ___ songs every day.» Выбери правильную форму глагола.","variants":["sings","singed","sing","singing"],"answer":["sing"]},
    {"question":"«I ___ songs every day.» Выбери правильную форму глагола.","variants":["singing","sing","singed","sings"],"answer":["sing"]},
    {"question":"«You ___ songs every day.» Выбери правильную форму глагола.","variants":["singing","sing","singed","sings"],"answer":["sing"]},
    {"question":"«He ___ a lot every day.» Выбери правильную форму глагола.","variants":["dances","dancesing","dance","danceed"],"answer":["dances"]},
    {"question":"«She ___ a lot every day.» Выбери правильную форму глагола.","variants":["dancesing","danceed","dance","dances"],"answer":["dances"]},
    {"question":"«They ___ a lot every day.» Выбери правильную форму глагола.","variants":["dances","danceing","danceed","dance"],"answer":["dance"]},
    {"question":"«We ___ a lot every day.» Выбери правильную форму глагола.","variants":["dance","danceing","danceed","dances"],"answer":["dance"]},
    {"question":"«I ___ a lot every day.» Выбери правильную форму глагола.","variants":["dance","danceed","dances","danceing"],"answer":["dance"]},
    {"question":"«You ___ a lot every day.» Выбери правильную форму глагола.","variants":["dances","danceed","danceing","dance"],"answer":["dance"]},
    {"question":"«He ___ pictures every day.» Выбери правильную форму глагола.","variants":["drawsing","draws","draw","drawed"],"answer":["draws"]},
    {"question":"«She ___ pictures every day.» Выбери правильную форму глагола.","variants":["draw","drawsing","drawed","draws"],"answer":["draws"]},
    {"question":"«They ___ pictures every day.» Выбери правильную форму глагола.","variants":["draws","drawed","drawing","draw"],"answer":["draw"]},
    {"question":"«We ___ pictures every day.» Выбери правильную форму глагола.","variants":["draws","drawing","draw","drawed"],"answer":["draw"]},
    {"question":"«I ___ pictures every day.» Выбери правильную форму глагола.","variants":["drawed","drawing","draw","draws"],"answer":["draw"]},
    {"question":"«You ___ pictures every day.» Выбери правильную форму глагола.","variants":["draw","drawed","drawing","draws"],"answer":["draw"]},
    {"question":"«He ___ a letter every day.» Выбери правильную форму глагола.","variants":["writesing","writeed","writes","write"],"answer":["writes"]},
    {"question":"«She ___ a letter every day.» Выбери правильную форму глагола.","variants":["write","writeed","writes","writesing"],"answer":["writes"]},
    {"question":"«They ___ a letter every day.» Выбери правильную форму глагола.","variants":["writes","writeing","write","writeed"],"answer":["write"]},
    {"question":"«We ___ a letter every day.» Выбери правильную форму глагола.","variants":["writes","write","writeed","writeing"],"answer":["write"]},
    {"question":"«I ___ a letter every day.» Выбери правильную форму глагола.","variants":["writeed","write","writeing","writes"],"answer":["write"]},
    {"question":"«You ___ a letter every day.» Выбери правильную форму глагола.","variants":["writes","write","writeing","writeed"],"answer":["write"]},
    {"question":"«He ___ at the board every day.» Выбери правильную форму глагола.","variants":["looksing","looked","look","looks"],"answer":["looks"]},
    {"question":"«She ___ at the board every day.» Выбери правильную форму глагола.","variants":["looks","looked","look","looksing"],"answer":["looks"]},
    {"question":"«They ___ at the board every day.» Выбери правильную форму глагола.","variants":["looks","look","looking","looked"],"answer":["look"]},
    {"question":"«We ___ at the board every day.» Выбери правильную форму глагола.","variants":["look","looked","looks","looking"],"answer":["look"]},
    {"question":"«I ___ at the board every day.» Выбери правильную форму глагола.","variants":["looked","looks","looking","look"],"answer":["look"]},
    {"question":"«You ___ at the board every day.» Выбери правильную форму глагола.","variants":["looks","looking","looked","look"],"answer":["look"]},
    {"question":"«He ___ TV every day.» Выбери правильную форму глагола.","variants":["watchesing","watch","watched","watches"],"answer":["watches"]},
    {"question":"«She ___ TV every day.» Выбери правильную форму глагола.","variants":["watchesing","watched","watches","watch"],"answer":["watches"]},
    {"question":"«They ___ TV every day.» Выбери правильную форму глагола.","variants":["watched","watch","watches","watching"],"answer":["watch"]},
    {"question":"«We ___ TV every day.» Выбери правильную форму глагола.","variants":["watching","watch","watched","watches"],"answer":["watch"]},
    {"question":"«I ___ TV every day.» Выбери правильную форму глагола.","variants":["watched","watch","watching","watches"],"answer":["watch"]},
    {"question":"«You ___ TV every day.» Выбери правильную форму глагола.","variants":["watching","watch","watches","watched"],"answer":["watch"]},
    {"question":"«He ___ the dishes every day.» Выбери правильную форму глагола.","variants":["washesing","washes","wash","washed"],"answer":["washes"]},
    {"question":"«She ___ the dishes every day.» Выбери правильную форму глагола.","variants":["washed","washes","wash","washesing"],"answer":["washes"]},
    {"question":"«They ___ the dishes every day.» Выбери правильную форму глагола.","variants":["washing","wash","washed","washes"],"answer":["wash"]},
    {"question":"«We ___ the dishes every day.» Выбери правильную форму глагола.","variants":["washed","wash","washing","washes"],"answer":["wash"]},
  ]
};
