export default {
  "title": "Артикли a/an",
  "questions": [
    {"question":"Выбери правильный артикль: ___ cat.","variants":["a","an","the"],"answer":["a"]},
    {"question":"«I see ___ cat.» Выбери правильный артикль.","variants":["the","a","an"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ dog.","variants":["a","an","the"],"answer":["a"]},
    {"question":"«I see ___ dog.» Выбери правильный артикль.","variants":["the","an","a"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ pen.","variants":["the","a","an"],"answer":["a"]},
    {"question":"«I see ___ pen.» Выбери правильный артикль.","variants":["an","a","the"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ book.","variants":["a","an","the"],"answer":["a"]},
    {"question":"«I see ___ book.» Выбери правильный артикль.","variants":["the","a","an"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ ball.","variants":["an","the","a"],"answer":["a"]},
    {"question":"«I see ___ ball.» Выбери правильный артикль.","variants":["the","an","a"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ car.","variants":["a","an","the"],"answer":["a"]},
    {"question":"«I see ___ car.» Выбери правильный артикль.","variants":["an","a","the"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ house.","variants":["a","an","the"],"answer":["a"]},
    {"question":"«I see ___ house.» Выбери правильный артикль.","variants":["a","the","an"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ table.","variants":["an","a","the"],"answer":["a"]},
    {"question":"«I see ___ table.» Выбери правильный артикль.","variants":["a","the","an"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ school.","variants":["a","an","the"],"answer":["a"]},
    {"question":"«I see ___ school.» Выбери правильный артикль.","variants":["an","a","the"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ boy.","variants":["an","a","the"],"answer":["a"]},
    {"question":"«I see ___ boy.» Выбери правильный артикль.","variants":["the","an","a"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ girl.","variants":["a","the","an"],"answer":["a"]},
    {"question":"«I see ___ girl.» Выбери правильный артикль.","variants":["a","an","the"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ friend.","variants":["the","a","an"],"answer":["a"]},
    {"question":"«I see ___ friend.» Выбери правильный артикль.","variants":["an","a","the"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ teacher.","variants":["an","the","a"],"answer":["a"]},
    {"question":"«I see ___ teacher.» Выбери правильный артикль.","variants":["an","a","the"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ pupil.","variants":["an","a","the"],"answer":["a"]},
    {"question":"«I see ___ pupil.» Выбери правильный артикль.","variants":["an","a","the"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ window.","variants":["an","a","the"],"answer":["a"]},
    {"question":"«I see ___ window.» Выбери правильный артикль.","variants":["the","an","a"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ chair.","variants":["a","the","an"],"answer":["a"]},
    {"question":"«I see ___ chair.» Выбери правильный артикль.","variants":["a","the","an"],"answer":["a"]},
    {"question":"Выбери правильный артикль: ___ apple.","variants":["an","a","the"],"answer":["an"]},
    {"question":"«I see ___ apple.» Выбери правильный артикль.","variants":["the","a","an"],"answer":["an"]},
    {"question":"Выбери правильный артикль: ___ orange.","variants":["a","the","an"],"answer":["an"]},
    {"question":"«I see ___ orange.» Выбери правильный артикль.","variants":["an","the","a"],"answer":["an"]},
    {"question":"Выбери правильный артикль: ___ egg.","variants":["a","the","an"],"answer":["an"]},
    {"question":"«I see ___ egg.» Выбери правильный артикль.","variants":["a","an","the"],"answer":["an"]},
    {"question":"Выбери правильный артикль: ___ elephant.","variants":["an","the","a"],"answer":["an"]},
    {"question":"«I see ___ elephant.» Выбери правильный артикль.","variants":["the","an","a"],"answer":["an"]},
    {"question":"Выбери правильный артикль: ___ umbrella.","variants":["a","the","an"],"answer":["an"]},
    {"question":"«I see ___ umbrella.» Выбери правильный артикль.","variants":["the","an","a"],"answer":["an"]},
    {"question":"Выбери правильный артикль: ___ ice cream.","variants":["a","the","an"],"answer":["an"]},
    {"question":"«I see ___ ice cream.» Выбери правильный артикль.","variants":["an","a","the"],"answer":["an"]},
    {"question":"Выбери правильный артикль: ___ eraser.","variants":["a","an","the"],"answer":["an"]},
    {"question":"«I see ___ eraser.» Выбери правильный артикль.","variants":["an","the","a"],"answer":["an"]},
    {"question":"Выбери правильный артикль: ___ arm.","variants":["a","the","an"],"answer":["an"]},
    {"question":"«I see ___ arm.» Выбери правильный артикль.","variants":["an","a","the"],"answer":["an"]},
    {"question":"Выбери правильный артикль: ___ ear.","variants":["an","the","a"],"answer":["an"]},
    {"question":"«I see ___ ear.» Выбери правильный артикль.","variants":["an","the","a"],"answer":["an"]},
    {"question":"Выбери правильный артикль: ___ eye.","variants":["an","the","a"],"answer":["an"]},
    {"question":"«I see ___ eye.» Выбери правильный артикль.","variants":["an","a","the"],"answer":["an"]},
    {"question":"Выбери правильный артикль: ___ owl.","variants":["the","a","an"],"answer":["an"]},
    {"question":"«I see ___ owl.» Выбери правильный артикль.","variants":["the","a","an"],"answer":["an"]},
    {"question":"Выбери правильный артикль: ___ actor.","variants":["the","an","a"],"answer":["an"]},
    {"question":"«I see ___ actor.» Выбери правильный артикль.","variants":["a","an","the"],"answer":["an"]},
    {"question":"Выбери правильный артикль: ___ animal.","variants":["the","an","a"],"answer":["an"]},
    {"question":"«I see ___ animal.» Выбери правильный артикль.","variants":["the","an","a"],"answer":["an"]},
    {"question":"Выбери правильный артикль: ___ island.","variants":["a","an","the"],"answer":["an"]},
    {"question":"«I see ___ island.» Выбери правильный артикль.","variants":["the","an","a"],"answer":["an"]},
    {"question":"Перед какими словами ставится артикль «an»?","variants":["перед словами, начинающимися с гласного звука","перед словами с гласного звука","никогда","перед любыми словами"],"answer":["перед словами, начинающимися с гласного звука"]},
  ]
};
