export default {
  "title": "Множественное число существительных",
  "questions": [
    {"question":"Один cat — два ___.","variants":["cats","stories","dogs","cities"],"answer":["cats"]},
    {"question":"Один dog — два ___.","variants":["babies","boys","foxes","dogs"],"answer":["dogs"]},
    {"question":"Один book — два ___.","variants":["berries","teachers","books","families"],"answer":["books"]},
    {"question":"Один pen — два ___.","variants":["stories","women","books","pens"],"answer":["pens"]},
    {"question":"Один table — два ___.","variants":["watches","pens","tables","bags"],"answer":["tables"]},
    {"question":"Один ball — два ___.","variants":["boys","dishes","balls","pens"],"answer":["balls"]},
    {"question":"Один car — два ___.","variants":["pens","teeth","balls","cars"],"answer":["cars"]},
    {"question":"Один bag — два ___.","variants":["bags","stories","cats","mice"],"answer":["bags"]},
    {"question":"Один girl — два ___.","variants":["children","girls","cars","classes"],"answer":["girls"]},
    {"question":"Один boy — два ___.","variants":["boys","dishes","brushes","buses"],"answer":["boys"]},
    {"question":"Один apple — два ___.","variants":["sheep","friends","teeth","apples"],"answer":["apples"]},
    {"question":"Один friend — два ___.","variants":["buses","friends","pens","teachers"],"answer":["friends"]},
    {"question":"Один teacher — два ___.","variants":["children","teachers","buses","families"],"answer":["teachers"]},
    {"question":"Один chair — два ___.","variants":["teeth","mice","dishes","chairs"],"answer":["chairs"]},
    {"question":"Один box — два ___.","variants":["boxes","pens","berries","watches"],"answer":["boxes"]},
    {"question":"Один bus — два ___.","variants":["watches","dogs","buses","boxes"],"answer":["buses"]},
    {"question":"Один dish — два ___.","variants":["dishes","sandwiches","feet","children"],"answer":["dishes"]},
    {"question":"Один watch — два ___.","variants":["girls","cities","mice","watches"],"answer":["watches"]},
    {"question":"Один fox — два ___.","variants":["mice","women","pens","foxes"],"answer":["foxes"]},
    {"question":"Один class — два ___.","variants":["classes","apples","mice","children"],"answer":["classes"]},
    {"question":"Один brush — два ___.","variants":["boxes","balls","brushes","buses"],"answer":["brushes"]},
    {"question":"Один sandwich — два ___.","variants":["dishes","friends","sandwiches","books"],"answer":["sandwiches"]},
    {"question":"Один baby — два ___.","variants":["dogs","boxes","babies","cars"],"answer":["babies"]},
    {"question":"Один city — два ___.","variants":["girls","cities","dishes","babies"],"answer":["cities"]},
    {"question":"Один story — два ___.","variants":["babies","mice","stories","cars"],"answer":["stories"]},
    {"question":"Один family — два ___.","variants":["families","women","cities","foxes"],"answer":["families"]},
    {"question":"Один berry — два ___.","variants":["cars","berries","babies","women"],"answer":["berries"]},
    {"question":"Один child — два ___.","variants":["tables","mice","berries","children"],"answer":["children"]},
    {"question":"Как правильно написать слово «children» во множественном числе?","variants":["sandwiches","apples","children","teachers"],"answer":["children"]},
    {"question":"Один mouse — два ___.","variants":["boys","cats","girls","mice"],"answer":["mice"]},
    {"question":"Как правильно написать слово «mice» во множественном числе?","variants":["boys","foxes","books","mice"],"answer":["mice"]},
    {"question":"Один foot — два ___.","variants":["geese","babies","buses","feet"],"answer":["feet"]},
    {"question":"Как правильно написать слово «feet» во множественном числе?","variants":["fish","cars","feet","apples"],"answer":["feet"]},
    {"question":"Один man — два ___.","variants":["foxes","dishes","pens","men"],"answer":["men"]},
    {"question":"Как правильно написать слово «men» во множественном числе?","variants":["brushes","fish","men","babies"],"answer":["men"]},
    {"question":"Один woman — два ___.","variants":["watches","women","buses","dishes"],"answer":["women"]},
    {"question":"Как правильно написать слово «women» во множественном числе?","variants":["women","children","dishes","girls"],"answer":["women"]},
    {"question":"Один tooth — два ___.","variants":["books","teeth","women","watches"],"answer":["teeth"]},
    {"question":"Как правильно написать слово «teeth» во множественном числе?","variants":["teeth","children","families","stories"],"answer":["teeth"]},
    {"question":"Один goose — два ___.","variants":["watches","women","geese","boys"],"answer":["geese"]},
    {"question":"Как правильно написать слово «geese» во множественном числе?","variants":["geese","families","foxes","chairs"],"answer":["geese"]},
    {"question":"Один fish — два ___.","variants":["apples","fish","buses","women"],"answer":["fish"]},
    {"question":"Как правильно написать слово «fish» во множественном числе?","variants":["tables","watches","children","fish"],"answer":["fish"]},
    {"question":"Один sheep — два ___.","variants":["mice","cars","sheep","foxes"],"answer":["sheep"]},
    {"question":"Как правильно написать слово «sheep» во множественном числе?","variants":["feet","sandwiches","tables","sheep"],"answer":["sheep"]},
    {"question":"Как образуется множественное число у слова «box»?","variants":["boxies","boxs","boxes","box"],"answer":["boxes"]},
    {"question":"Как образуется множественное число у слова «city»?","variants":["cityes","citys","city","cities"],"answer":["cities"]},
    {"question":"Какое множественное число у слова «man»?","variants":["man","mans","manes","men"],"answer":["men"]},
    {"question":"Какое множественное число у слова «child»?","variants":["childes","children","childs","child"],"answer":["children"]},
  ]
};
