export default {
  "title": "Указательные местоимения this/that/these/those",
  "questions": [
    {"question":"Рядом со мной (близко) лежит ___ book. (ед.ч.)","variants":["these","those","that","this"],"answer":["this"]},
    {"question":"Рядом со мной (близко) лежит ___ ball. (ед.ч.)","variants":["those","that","this","these"],"answer":["this"]},
    {"question":"Рядом со мной (близко) лежит ___ cat. (ед.ч.)","variants":["these","this","those","that"],"answer":["this"]},
    {"question":"Рядом со мной (близко) лежит ___ pen. (ед.ч.)","variants":["those","that","this","these"],"answer":["this"]},
    {"question":"Рядом со мной (близко) лежит ___ apple. (ед.ч.)","variants":["this","those","these","that"],"answer":["this"]},
    {"question":"Рядом со мной (близко) лежит ___ dog. (ед.ч.)","variants":["this","that","those","these"],"answer":["this"]},
    {"question":"Рядом со мной (близко) лежит ___ cup. (ед.ч.)","variants":["this","these","that","those"],"answer":["this"]},
    {"question":"Рядом со мной (близко) лежит ___ toy. (ед.ч.)","variants":["that","these","this","those"],"answer":["this"]},
    {"question":"Рядом со мной (близко) лежит ___ car. (ед.ч.)","variants":["these","this","that","those"],"answer":["this"]},
    {"question":"Рядом со мной (близко) лежит ___ bird. (ед.ч.)","variants":["that","those","this","these"],"answer":["this"]},
    {"question":"Рядом со мной (близко) лежит ___ tree. (ед.ч.)","variants":["this","those","that","these"],"answer":["this"]},
    {"question":"Рядом со мной (близко) лежит ___ house. (ед.ч.)","variants":["this","those","these","that"],"answer":["this"]},
    {"question":"Рядом со мной (близко) лежит ___ carrot. (ед.ч.)","variants":["those","that","this","these"],"answer":["this"]},
    {"question":"Рядом со мной (близко) лежит ___ kite. (ед.ч.)","variants":["these","those","this","that"],"answer":["this"]},
    {"question":"Рядом со мной (близко) лежит ___ ship. (ед.ч.)","variants":["those","that","this","these"],"answer":["this"]},
    {"question":"Далеко от меня стоит ___ book. (ед.ч.)","variants":["this","those","that","these"],"answer":["that"]},
    {"question":"Далеко от меня стоит ___ ball. (ед.ч.)","variants":["these","that","this","those"],"answer":["that"]},
    {"question":"Далеко от меня стоит ___ cat. (ед.ч.)","variants":["these","that","those","this"],"answer":["that"]},
    {"question":"Далеко от меня стоит ___ pen. (ед.ч.)","variants":["this","that","these","those"],"answer":["that"]},
    {"question":"Далеко от меня стоит ___ apple. (ед.ч.)","variants":["that","those","these","this"],"answer":["that"]},
    {"question":"Далеко от меня стоит ___ dog. (ед.ч.)","variants":["those","that","this","these"],"answer":["that"]},
    {"question":"Далеко от меня стоит ___ cup. (ед.ч.)","variants":["this","that","these","those"],"answer":["that"]},
    {"question":"Далеко от меня стоит ___ toy. (ед.ч.)","variants":["these","that","those","this"],"answer":["that"]},
    {"question":"Далеко от меня стоит ___ car. (ед.ч.)","variants":["this","those","these","that"],"answer":["that"]},
    {"question":"Далеко от меня стоит ___ bird. (ед.ч.)","variants":["that","those","this","these"],"answer":["that"]},
    {"question":"Далеко от меня стоит ___ tree. (ед.ч.)","variants":["that","this","those","these"],"answer":["that"]},
    {"question":"Далеко от меня стоит ___ house. (ед.ч.)","variants":["these","this","those","that"],"answer":["that"]},
    {"question":"Далеко от меня стоит ___ carrot. (ед.ч.)","variants":["this","these","that","those"],"answer":["that"]},
    {"question":"Далеко от меня стоит ___ kite. (ед.ч.)","variants":["this","these","those","that"],"answer":["that"]},
    {"question":"Далеко от меня стоит ___ ship. (ед.ч.)","variants":["these","those","this","that"],"answer":["that"]},
    {"question":"Рядом со мной (близко) лежат ___ books and pens. (мн.ч.)","variants":["those","this","these","that"],"answer":["these"]},
    {"question":"Рядом со мной (близко) лежат ___ cats. (мн.ч.)","variants":["that","those","this","these"],"answer":["these"]},
    {"question":"Рядом со мной (близко) лежат ___ balls. (мн.ч.)","variants":["these","that","this","those"],"answer":["these"]},
    {"question":"Рядом со мной (близко) лежат ___ pens. (мн.ч.)","variants":["those","that","these","this"],"answer":["these"]},
    {"question":"Рядом со мной (близко) лежат ___ apples. (мн.ч.)","variants":["these","this","that","those"],"answer":["these"]},
    {"question":"Рядом со мной (близко) лежат ___ dogs. (мн.ч.)","variants":["that","these","this","those"],"answer":["these"]},
    {"question":"Рядом со мной (близко) лежат ___ cups. (мн.ч.)","variants":["this","these","those","that"],"answer":["these"]},
    {"question":"Рядом со мной (близко) лежат ___ toys. (мн.ч.)","variants":["those","this","these","that"],"answer":["these"]},
    {"question":"Рядом со мной (близко) лежат ___ birds. (мн.ч.)","variants":["this","that","those","these"],"answer":["these"]},
    {"question":"Рядом со мной (близко) лежат ___ trees. (мн.ч.)","variants":["those","this","these","that"],"answer":["these"]},
    {"question":"Рядом со мной (близко) лежат ___ kites. (мн.ч.)","variants":["that","these","those","this"],"answer":["these"]},
    {"question":"Рядом со мной (близко) лежат ___ ships. (мн.ч.)","variants":["this","these","that","those"],"answer":["these"]},
    {"question":"Далеко от меня стоят ___ books and pens. (мн.ч.)","variants":["that","this","these","those"],"answer":["those"]},
    {"question":"Далеко от меня стоят ___ cats. (мн.ч.)","variants":["these","this","those","that"],"answer":["those"]},
    {"question":"Далеко от меня стоят ___ balls. (мн.ч.)","variants":["this","these","those","that"],"answer":["those"]},
    {"question":"Далеко от меня стоят ___ pens. (мн.ч.)","variants":["those","these","that","this"],"answer":["those"]},
    {"question":"Далеко от меня стоят ___ apples. (мн.ч.)","variants":["this","these","those","that"],"answer":["those"]},
    {"question":"Далеко от меня стоят ___ dogs. (мн.ч.)","variants":["this","that","those","these"],"answer":["those"]},
    {"question":"Далеко от меня стоят ___ cups. (мн.ч.)","variants":["this","those","that","these"],"answer":["those"]},
    {"question":"Далеко от меня стоят ___ toys. (мн.ч.)","variants":["these","that","this","those"],"answer":["those"]},
    {"question":"Далеко от меня стоят ___ birds. (мн.ч.)","variants":["these","those","this","that"],"answer":["those"]},
    {"question":"Далеко от меня стоят ___ trees. (мн.ч.)","variants":["that","these","this","those"],"answer":["those"]},
    {"question":"Далеко от меня стоят ___ kites. (мн.ч.)","variants":["this","that","those","these"],"answer":["those"]},
    {"question":"Далеко от меня стоят ___ ships. (мн.ч.)","variants":["those","these","this","that"],"answer":["those"]},
    {"question":"Какое слово мы используем, когда предмет близко и один?","variants":["those","this","these","that"],"answer":["this"]},
    {"question":"Какое слово мы используем, когда предмет далеко и их несколько?","variants":["these","this","that","those"],"answer":["those"]},
    {"question":"Какое слово мы используем, когда предметы близко и их несколько?","variants":["this","that","these","those"],"answer":["these"]},
    {"question":"Какое слово мы используем, когда предмет далеко и он один?","variants":["those","this","these","that"],"answer":["that"]},
    {"question":"«___ is my book» (книга рядом, одна).","variants":["Those","These","This","That"],"answer":["This"]},
    {"question":"«___ are my pens» (ручки далеко, много).","variants":["This","These","Those","That"],"answer":["Those"]},
    {"question":"«Look at ___ bird» (птица далеко).","variants":["these","those","this","that"],"answer":["that"]},
    {"question":"«Look at ___ birds» (птицы близко).","variants":["that","those","these","this"],"answer":["these"]},
  ]
};
