export default {
  "title": "Вопросительные слова (what/where/when/who/why/how)",
  "questions": [
    {"question":"Как по-английски вопрос «Что?»?","variants":["What","How many","Who","Why"],"answer":["What"]},
    {"question":"Как по-английски вопрос «Где?»?","variants":["Who","Where","What","When"],"answer":["Where"]},
    {"question":"Как по-английски вопрос «Когда?»?","variants":["Who","How","When","What"],"answer":["When"]},
    {"question":"Как по-английски вопрос «Кто?»?","variants":["How","What","When","Who"],"answer":["Who"]},
    {"question":"Как по-английски вопрос «Почему?»?","variants":["Where","Who","When","Why"],"answer":["Why"]},
    {"question":"Как по-английски вопрос «Как?»?","variants":["How many","How","What","Where"],"answer":["How"]},
    {"question":"Как по-английски вопрос «Сколько?»?","variants":["What","Where","When","How many"],"answer":["How many"]},
    {"question":"Как по-английски вопрос «Который час?»?","variants":["Where","Why","How many","What time"],"answer":["What time"]},
    {"question":"___ is your name?","variants":["Who","When","Why","What"],"answer":["What"]},
    {"question":"___ do you live?","variants":["Who","When","Where","How"],"answer":["Where"]},
    {"question":"___ is your birthday?","variants":["When","How","Why","Where"],"answer":["When"]},
    {"question":"___ is that girl? (кто)","variants":["When","Where","What","Who"],"answer":["Who"]},
    {"question":"___ are you sad?","variants":["Why","What","Who","When"],"answer":["Why"]},
    {"question":"___ old are you?","variants":["Why","Who","What","How"],"answer":["How"]},
    {"question":"___ is your book? (где)","variants":["Where","What","Why","How"],"answer":["Where"]},
    {"question":"___ is your favourite toy? (что)","variants":["What","Where","When","Why"],"answer":["What"]},
    {"question":"___ is your teacher? (кто)","variants":["What","Who","Where","How"],"answer":["Who"]},
    {"question":"___ do you get up? (когда)","variants":["What","Why","When","How"],"answer":["When"]},
    {"question":"___ many pens do you have?","variants":["Where","How","When","What"],"answer":["How"]},
    {"question":"___ are you late?","variants":["What","Who","Why","When"],"answer":["Why"]},
    {"question":"С какого слова начинается вопрос о месте?","variants":["What","How","Who","Where"],"answer":["Where"]},
    {"question":"С какого слова начинается вопрос о времени?","variants":["What","Where","When","How"],"answer":["When"]},
    {"question":"С какого слова начинается вопрос о человеке?","variants":["Who","When","What","Where"],"answer":["Who"]},
    {"question":"С какого слова начинается вопрос о причине?","variants":["How","What","Why","Who"],"answer":["Why"]},
    {"question":"С какого слова начинается вопрос о количестве?","variants":["Why","When","How","What"],"answer":["How"]},
    {"question":"С какого слова начинается вопрос о предмете?","variants":["What","Why","Who","How"],"answer":["What"]},
    {"question":"Как спросить «Где ты живёшь?»","variants":["How do you live?","When do you live?","Where do you live?","What do you live?"],"answer":["Where do you live?"]},
    {"question":"Как спросить «Сколько тебе лет?»","variants":["What old are you?","Why old are you?","How old are you?","Who old are you?"],"answer":["How old are you?"]},
    {"question":"Как спросить «Что это?»","variants":["Who is it?","What is it?","Where is it?","When is it?"],"answer":["What is it?"]},
    {"question":"Как спросить «Кто это?»","variants":["What is it?","Who is it?","Where is it?","How is it?"],"answer":["Who is it?"]},
  ]
};
