export default {
  "title": "Оборот have got / has got",
  "questions": [
    {"question":"«I ___ a cat.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«I ___ a dog.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«I ___ a bike.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«I ___ a ball.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«I ___ a book.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«I ___ a doll.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«I ___ two brothers.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«I ___ a sister.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«I ___ a nice room.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«I ___ many toys.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«I ___ a new pen.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«I ___ a big house.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«You ___ a cat.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«You ___ a dog.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«You ___ a bike.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«You ___ a ball.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«You ___ a book.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«You ___ a doll.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«You ___ two brothers.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«You ___ a sister.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«You ___ a nice room.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«You ___ many toys.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«You ___ a new pen.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«You ___ a big house.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«We ___ a cat.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«We ___ a dog.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«We ___ a bike.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«We ___ a ball.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«We ___ a book.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«We ___ a doll.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«We ___ two brothers.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«We ___ a sister.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«We ___ a nice room.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«We ___ many toys.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«We ___ a new pen.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«We ___ a big house.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«They ___ a cat.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«They ___ a dog.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«They ___ a bike.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«They ___ a ball.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«They ___ a book.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«They ___ a doll.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«They ___ two brothers.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«They ___ a sister.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«They ___ a nice room.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«They ___ many toys.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«They ___ a new pen.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«They ___ a big house.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«The boys ___ a cat.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«The boys ___ a dog.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«The boys ___ a bike.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«The boys ___ a ball.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«The boys ___ a book.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«The boys ___ a doll.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«The boys ___ two brothers.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«The boys ___ a sister.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«The boys ___ a nice room.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«The boys ___ many toys.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«The boys ___ a new pen.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«The boys ___ a big house.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«My friends ___ a cat.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«My friends ___ a dog.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«My friends ___ a bike.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«My friends ___ a ball.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«My friends ___ a book.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«My friends ___ a doll.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«My friends ___ two brothers.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«My friends ___ a sister.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«My friends ___ a nice room.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«My friends ___ many toys.» Выбери правильную форму.","variants":["has got","have got"],"answer":["have got"]},
    {"question":"«My friends ___ a new pen.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«My friends ___ a big house.» Выбери правильную форму.","variants":["have got","has got"],"answer":["have got"]},
    {"question":"«He ___ a cat.» Выбери правильную форму.","variants":["have got","has got"],"answer":["has got"]},
    {"question":"«He ___ a dog.» Выбери правильную форму.","variants":["have got","has got"],"answer":["has got"]},
    {"question":"«He ___ a bike.» Выбери правильную форму.","variants":["has got","have got"],"answer":["has got"]},
    {"question":"«He ___ a ball.» Выбери правильную форму.","variants":["have got","has got"],"answer":["has got"]},
    {"question":"«He ___ a book.» Выбери правильную форму.","variants":["has got","have got"],"answer":["has got"]},
    {"question":"«He ___ a doll.» Выбери правильную форму.","variants":["has got","have got"],"answer":["has got"]},
    {"question":"«He ___ two brothers.» Выбери правильную форму.","variants":["has got","have got"],"answer":["has got"]},
    {"question":"«He ___ a sister.» Выбери правильную форму.","variants":["has got","have got"],"answer":["has got"]},
    {"question":"«He ___ a nice room.» Выбери правильную форму.","variants":["has got","have got"],"answer":["has got"]},
    {"question":"«He ___ many toys.» Выбери правильную форму.","variants":["have got","has got"],"answer":["has got"]},
    {"question":"«He ___ a new pen.» Выбери правильную форму.","variants":["has got","have got"],"answer":["has got"]},
    {"question":"«He ___ a big house.» Выбери правильную форму.","variants":["have got","has got"],"answer":["has got"]},
    {"question":"«She ___ a cat.» Выбери правильную форму.","variants":["have got","has got"],"answer":["has got"]},
    {"question":"«She ___ a dog.» Выбери правильную форму.","variants":["has got","have got"],"answer":["has got"]},
    {"question":"«She ___ a bike.» Выбери правильную форму.","variants":["has got","have got"],"answer":["has got"]},
    {"question":"«She ___ a ball.» Выбери правильную форму.","variants":["has got","have got"],"answer":["has got"]},
    {"question":"«She ___ a book.» Выбери правильную форму.","variants":["have got","has got"],"answer":["has got"]},
    {"question":"«She ___ a doll.» Выбери правильную форму.","variants":["has got","have got"],"answer":["has got"]},
    {"question":"«She ___ two brothers.» Выбери правильную форму.","variants":["have got","has got"],"answer":["has got"]},
    {"question":"«She ___ a sister.» Выбери правильную форму.","variants":["have got","has got"],"answer":["has got"]},
    {"question":"«She ___ a nice room.» Выбери правильную форму.","variants":["has got","have got"],"answer":["has got"]},
    {"question":"«She ___ many toys.» Выбери правильную форму.","variants":["have got","has got"],"answer":["has got"]},
    {"question":"«She ___ a new pen.» Выбери правильную форму.","variants":["have got","has got"],"answer":["has got"]},
    {"question":"«She ___ a big house.» Выбери правильную форму.","variants":["have got","has got"],"answer":["has got"]},
    {"question":"«It ___ a cat.» Выбери правильную форму.","variants":["has got","have got"],"answer":["has got"]},
    {"question":"«It ___ a dog.» Выбери правильную форму.","variants":["have got","has got"],"answer":["has got"]},
    {"question":"«It ___ a bike.» Выбери правильную форму.","variants":["have got","has got"],"answer":["has got"]},
    {"question":"«It ___ a ball.» Выбери правильную форму.","variants":["has got","have got"],"answer":["has got"]},
  ]
};
