export default {
  "title": "Личные местоимения (I/he/she/it/we/they)",
  "questions": [
    {"question":"Замени подлежащее местоимением: «Ann is my friend.»","variants":["You","He","She","I"],"answer":["She"]},
    {"question":"Замени подлежащее местоимением: «Tom is a pupil.»","variants":["He","We","I","You"],"answer":["He"]},
    {"question":"Замени подлежащее местоимением: «The cat is black.»","variants":["It","You","He","I"],"answer":["It"]},
    {"question":"Замени подлежащее местоимением: «Mum and Dad are at home.»","variants":["You","She","They","He"],"answer":["They"]},
    {"question":"Замени подлежащее местоимением: «My friend and I play.»","variants":["I","They","We","She"],"answer":["We"]},
    {"question":"Замени подлежащее местоимением: «The boys are happy.»","variants":["They","He","It","You"],"answer":["They"]},
    {"question":"Замени подлежащее местоимением: «The dog runs.»","variants":["It","She","You","They"],"answer":["It"]},
    {"question":"Замени подлежащее местоимением: «My sister sings.»","variants":["We","They","She","You"],"answer":["She"]},
    {"question":"Замени подлежащее местоимением: «My brother draws.»","variants":["It","You","He","We"],"answer":["He"]},
    {"question":"Замени подлежащее местоимением: «The children sleep.»","variants":["He","I","They","You"],"answer":["They"]},
    {"question":"Замени подлежащее местоимением: «The book is on the table.»","variants":["It","He","We","You"],"answer":["It"]},
    {"question":"Замени подлежащее местоимением: «Kate is a doctor.»","variants":["It","They","She","We"],"answer":["She"]},
    {"question":"Замени подлежащее местоимением: «Peter is a student.»","variants":["He","It","I","We"],"answer":["He"]},
    {"question":"Замени подлежащее местоимением: «The girls play tennis.»","variants":["She","They","You","We"],"answer":["They"]},
    {"question":"Замени подлежащее местоимением: «My teacher is kind.»","variants":["I","It","She","They"],"answer":["She"]},
    {"question":"Замени подлежащее местоимением: «The bird sings.»","variants":["They","It","He","You"],"answer":["It"]},
    {"question":"Замени подлежащее местоимением: «Grandma and I cook.»","variants":["You","It","She","We"],"answer":["We"]},
    {"question":"Замени подлежащее местоимением: «The cat drinks milk.»","variants":["We","She","It","I"],"answer":["It"]},
    {"question":"Замени подлежащее местоимением: «Nina swims well.»","variants":["He","We","She","I"],"answer":["She"]},
    {"question":"Замени подлежащее местоимением: «Mike helps his mum.»","variants":["We","He","It","You"],"answer":["He"]},
    {"question":"Замени подлежащее местоимением: «The pupils read.»","variants":["They","You","We","She"],"answer":["They"]},
    {"question":"Замени подлежащее местоимением: «Mum reads a book.»","variants":["He","I","We","She"],"answer":["She"]},
    {"question":"Замени подлежащее местоимением: «Dad works in the garden.»","variants":["She","We","He","It"],"answer":["He"]},
    {"question":"Замени подлежащее местоимением: «The birds fly.»","variants":["I","They","She","He"],"answer":["They"]},
    {"question":"Замени подлежащее местоимением: «The sun is bright.»","variants":["It","They","You","I"],"answer":["It"]},
    {"question":"Замени подлежащее местоимением: «My friends are funny.»","variants":["We","They","He","You"],"answer":["They"]},
    {"question":"Замени подлежащее местоимением: «My dog likes bones.»","variants":["You","It","He","I"],"answer":["It"]},
    {"question":"Замени подлежащее местоимением: «The lion is big.»","variants":["He","I","You","It"],"answer":["It"]},
    {"question":"Замени подлежащее местоимением: «Oleg and I are friends.»","variants":["She","It","We","I"],"answer":["We"]},
    {"question":"Замени подлежащее местоимением: «Grandpa tells stories.»","variants":["She","We","They","He"],"answer":["He"]},
    {"question":"Замени «Ann» местоимением:","variants":["You","She","He","They"],"answer":["She"]},
    {"question":"Замени «Tom» местоимением:","variants":["We","She","He","They"],"answer":["He"]},
    {"question":"Замени «my friends» местоимением:","variants":["They","He","It","I"],"answer":["They"]},
    {"question":"Замени «the dog» местоимением:","variants":["He","She","They","It"],"answer":["It"]},
    {"question":"Замени «my friend and I» местоимением:","variants":["It","We","You","She"],"answer":["We"]},
    {"question":"Какое местоимение для слова «cat»?","variants":["She","It","They","I"],"answer":["It"]},
    {"question":"Какое местоимение для слова «girl»?","variants":["We","She","I","It"],"answer":["She"]},
    {"question":"Какое местоимение для слова «boy»?","variants":["He","It","I","She"],"answer":["He"]},
    {"question":"Какое местоимение для слова «children»?","variants":["You","She","I","They"],"answer":["They"]},
  ]
};
