export default {
  "title": "Школа и учебные предметы",
  "questions": [
    {"question":"Как по-английски «школа»?","variants":["a school","a ruler","PE","a teacher"],"answer":["a school"]},
    {"question":"Как переводится «a school»?","variants":["книга","школа","рисование","ученик"],"answer":["школа"]},
    {"question":"Как по-английски «класс»?","variants":["Science","a pupil","a bag","a class"],"answer":["a class"]},
    {"question":"Как переводится «a class»?","variants":["точилка","чтение","домашнее задание","класс"],"answer":["класс"]},
    {"question":"Как по-английски «учитель»?","variants":["a pupil","a rubber","a teacher","a classroom"],"answer":["a teacher"]},
    {"question":"Как переводится «a teacher»?","variants":["музыка","учитель","пенал","сумка, портфель"],"answer":["учитель"]},
    {"question":"Как по-английски «ученик»?","variants":["English","a pupil","Maths","a lesson"],"answer":["a pupil"]},
    {"question":"Как переводится «a pupil»?","variants":["парта","линейка","пенал","ученик"],"answer":["ученик"]},
    {"question":"Как по-английски «книга»?","variants":["a teacher","Art","a book","a notebook"],"answer":["a book"]},
    {"question":"Как переводится «a book»?","variants":["доска","книга","рисование","класс"],"answer":["книга"]},
    {"question":"Как по-английски «ручка»?","variants":["a notebook","a board","a pen","English"],"answer":["a pen"]},
    {"question":"Как переводится «a pen»?","variants":["ручка","линейка","урок","рисование"],"answer":["ручка"]},
    {"question":"Как по-английски «карандаш»?","variants":["a pupil","a pencil","a school","a class"],"answer":["a pencil"]},
    {"question":"Как переводится «a pencil»?","variants":["карандаш","стул","урок","школа"],"answer":["карандаш"]},
    {"question":"Как по-английски «ластик»?","variants":["PE","a bag","homework","a rubber"],"answer":["a rubber"]},
    {"question":"Как переводится «a rubber»?","variants":["природоведение","ластик","линейка","учитель"],"answer":["ластик"]},
    {"question":"Как по-английски «линейка»?","variants":["a lesson","a ruler","a school","a bag"],"answer":["a ruler"]},
    {"question":"Как переводится «a ruler»?","variants":["математика","линейка","парта","доска"],"answer":["линейка"]},
    {"question":"Как по-английски «пенал»?","variants":["a board","a chair","a pencil case","a ruler"],"answer":["a pencil case"]},
    {"question":"Как переводится «a pencil case»?","variants":["пенал","музыка","тетрадь","стул"],"answer":["пенал"]},
    {"question":"Как по-английски «сумка, портфель»?","variants":["a bag","a desk","homework","a rubber"],"answer":["a bag"]},
    {"question":"Как переводится «a bag»?","variants":["рисование","математика","сумка, портфель","ластик"],"answer":["сумка, портфель"]},
    {"question":"Как по-английски «точилка»?","variants":["Art","English","a pupil","a sharpener"],"answer":["a sharpener"]},
    {"question":"Как переводится «a sharpener»?","variants":["ученик","стул","точилка","учитель"],"answer":["точилка"]},
    {"question":"Как по-английски «парта»?","variants":["a pupil","a notebook","a desk","a teacher"],"answer":["a desk"]},
    {"question":"Как переводится «a desk»?","variants":["точилка","карандаш","учитель","парта"],"answer":["парта"]},
    {"question":"Как по-английски «стул»?","variants":["a chair","PE","Music","a classroom"],"answer":["a chair"]},
    {"question":"Как переводится «a chair»?","variants":["парта","тетрадь","линейка","стул"],"answer":["стул"]},
    {"question":"Как по-английски «доска»?","variants":["a board","English","Maths","a bag"],"answer":["a board"]},
    {"question":"Как переводится «a board»?","variants":["доска","точилка","карандаш","музыка"],"answer":["доска"]},
    {"question":"Как по-английски «тетрадь»?","variants":["a notebook","Music","a teacher","a classroom"],"answer":["a notebook"]},
    {"question":"Как переводится «a notebook»?","variants":["классная комната","ластик","тетрадь","школа"],"answer":["тетрадь"]},
    {"question":"Как по-английски «математика»?","variants":["Art","a bag","Maths","English"],"answer":["Maths"]},
    {"question":"Как переводится «Maths»?","variants":["стул","математика","домашнее задание","рисование"],"answer":["математика"]},
    {"question":"Как по-английски «музыка»?","variants":["a class","Music","a classroom","a pencil"],"answer":["Music"]},
    {"question":"Как переводится «Music»?","variants":["музыка","ученик","домашнее задание","класс"],"answer":["музыка"]},
    {"question":"Как по-английски «рисование»?","variants":["Art","a book","a teacher","a lesson"],"answer":["Art"]},
    {"question":"Как переводится «Art»?","variants":["линейка","ученик","рисование","карандаш"],"answer":["рисование"]},
    {"question":"Как по-английски «физкультура»?","variants":["homework","a classroom","a pencil case","PE"],"answer":["PE"]},
    {"question":"Как переводится «PE»?","variants":["природоведение","физкультура","стул","музыка"],"answer":["физкультура"]},
    {"question":"Как по-английски «английский язык»?","variants":["a board","a school","Reading","English"],"answer":["English"]},
    {"question":"Как переводится «English»?","variants":["тетрадь","английский язык","физкультура","чтение"],"answer":["английский язык"]},
    {"question":"Как по-английски «природоведение»?","variants":["a chair","Science","Reading","a classroom"],"answer":["Science"]},
    {"question":"Как переводится «Science»?","variants":["точилка","школа","природоведение","книга"],"answer":["природоведение"]},
    {"question":"Как по-английски «чтение»?","variants":["a ruler","a pencil case","Reading","a book"],"answer":["Reading"]},
    {"question":"Как переводится «Reading»?","variants":["домашнее задание","природоведение","чтение","физкультура"],"answer":["чтение"]},
    {"question":"Как по-английски «классная комната»?","variants":["a classroom","a school","a pencil","Science"],"answer":["a classroom"]},
    {"question":"Как переводится «a classroom»?","variants":["ластик","классная комната","рисование","урок"],"answer":["классная комната"]},
    {"question":"Как по-английски «урок»?","variants":["English","Science","a lesson","a book"],"answer":["a lesson"]},
    {"question":"Как переводится «a lesson»?","variants":["урок","английский язык","учитель","физкультура"],"answer":["урок"]},
    {"question":"Как по-английски «домашнее задание»?","variants":["a teacher","homework","a classroom","Reading"],"answer":["homework"]},
    {"question":"Как переводится «homework»?","variants":["музыка","физкультура","классная комната","домашнее задание"],"answer":["домашнее задание"]},
    {"question":"Как переводится «Stand up»?","variants":["Слушай","Встань","Повтори","Смотри"],"answer":["Встань"]},
    {"question":"Как по-английски «Встань»?","variants":["Close your book","Read","Stand up","Open your book"],"answer":["Stand up"]},
    {"question":"Как переводится «Sit down»?","variants":["Пиши","Сядь","Повтори","Читай"],"answer":["Сядь"]},
    {"question":"Как по-английски «Сядь»?","variants":["Open your book","Sit down","Draw","Listen"],"answer":["Sit down"]},
    {"question":"Как переводится «Open your book»?","variants":["Нарисуй","Повтори","Закрой","Открой книгу"],"answer":["Открой книгу"]},
    {"question":"Как по-английски «Открой книгу»?","variants":["Sit down","Read","Open your book","Draw"],"answer":["Open your book"]},
    {"question":"Как переводится «Close your book»?","variants":["Слушай","Пиши","Встань","Закрой книгу"],"answer":["Закрой книгу"]},
    {"question":"Как по-английски «Закрой книгу»?","variants":["Open your book","Close your book","Look","Sit down"],"answer":["Close your book"]},
    {"question":"Как переводится «Listen»?","variants":["Пиши","Повтори","Читай","Слушай"],"answer":["Слушай"]},
    {"question":"Как по-английски «Слушай»?","variants":["Listen","Sit down","Repeat","Look"],"answer":["Listen"]},
    {"question":"Как переводится «Look»?","variants":["Повтори","Встань","Слушай","Смотри"],"answer":["Смотри"]},
    {"question":"Как по-английски «Смотри»?","variants":["Listen","Read","Write","Look"],"answer":["Look"]},
    {"question":"Как переводится «Read»?","variants":["Повтори","Встань","Читай","Иди"],"answer":["Читай"]},
    {"question":"Как по-английски «Читай»?","variants":["Read","Listen","Look","Draw"],"answer":["Read"]},
    {"question":"Как переводится «Write»?","variants":["Слушай","Пиши","Закрой","Читай"],"answer":["Пиши"]},
    {"question":"Как по-английски «Пиши»?","variants":["Listen","Sit down","Write","Read"],"answer":["Write"]},
    {"question":"Как переводится «Repeat»?","variants":["Смотри","Повтори","Нарисуй","Иди"],"answer":["Повтори"]},
    {"question":"Как по-английски «Повтори»?","variants":["Stand up","Write","Close your book","Repeat"],"answer":["Repeat"]},
    {"question":"Как переводится «Draw»?","variants":["Читай","Сядь","Встань","Нарисуй"],"answer":["Нарисуй"]},
    {"question":"Как по-английски «Нарисуй»?","variants":["Read","Close your book","Draw","Look"],"answer":["Draw"]},
  ]
};
