export default {
  "title": "Знакомство, числа и цвета",
  "questions": [
    {"question":"Как по-английски «один»?","variants":["fifteen","one","four","twenty"],"answer":["one"]},
    {"question":"Как переводится «one»?","variants":["один","семь","восемь","девятнадцать"],"answer":["один"]},
    {"question":"Как по-английски «два»?","variants":["fourteen","two","seven","nineteen"],"answer":["two"]},
    {"question":"Как переводится «two»?","variants":["двадцать","два","пятнадцать","семнадцать"],"answer":["два"]},
    {"question":"Как по-английски «три»?","variants":["five","two","three","nineteen"],"answer":["three"]},
    {"question":"Как переводится «three»?","variants":["шесть","три","пятнадцать","девятнадцать"],"answer":["три"]},
    {"question":"Как по-английски «четыре»?","variants":["four","fourteen","twenty","three"],"answer":["four"]},
    {"question":"Как переводится «four»?","variants":["один","четыре","девять","три"],"answer":["четыре"]},
    {"question":"Как по-английски «пять»?","variants":["five","eight","fifteen","six"],"answer":["five"]},
    {"question":"Как переводится «five»?","variants":["двенадцать","шесть","пять","семнадцать"],"answer":["пять"]},
    {"question":"Как по-английски «шесть»?","variants":["twelve","six","fifteen","twenty"],"answer":["six"]},
    {"question":"Как переводится «six»?","variants":["двадцать","пять","восемнадцать","шесть"],"answer":["шесть"]},
    {"question":"Как по-английски «семь»?","variants":["nine","two","twenty","seven"],"answer":["seven"]},
    {"question":"Как переводится «seven»?","variants":["три","десять","семнадцать","семь"],"answer":["семь"]},
    {"question":"Как по-английски «восемь»?","variants":["one","eight","seventeen","five"],"answer":["eight"]},
    {"question":"Как переводится «eight»?","variants":["два","восемь","шесть","одиннадцать"],"answer":["восемь"]},
    {"question":"Как по-английски «девять»?","variants":["nine","sixteen","thirteen","ten"],"answer":["nine"]},
    {"question":"Как переводится «nine»?","variants":["семь","девять","десять","восемь"],"answer":["девять"]},
    {"question":"Как по-английски «десять»?","variants":["six","twenty","nineteen","ten"],"answer":["ten"]},
    {"question":"Как переводится «ten»?","variants":["восемнадцать","десять","один","четырнадцать"],"answer":["десять"]},
    {"question":"Как по-английски «одиннадцать»?","variants":["eleven","seven","eight","twelve"],"answer":["eleven"]},
    {"question":"Как переводится «eleven»?","variants":["восемь","шестнадцать","одиннадцать","три"],"answer":["одиннадцать"]},
    {"question":"Как по-английски «двенадцать»?","variants":["two","twelve","eight","nine"],"answer":["twelve"]},
    {"question":"Как переводится «twelve»?","variants":["четыре","семь","три","двенадцать"],"answer":["двенадцать"]},
    {"question":"Как по-английски «тринадцать»?","variants":["thirteen","three","four","two"],"answer":["thirteen"]},
    {"question":"Как переводится «thirteen»?","variants":["тринадцать","двенадцать","четырнадцать","восемнадцать"],"answer":["тринадцать"]},
    {"question":"Как по-английски «четырнадцать»?","variants":["eleven","fourteen","seventeen","nine"],"answer":["fourteen"]},
    {"question":"Как переводится «fourteen»?","variants":["восемнадцать","семнадцать","четырнадцать","четыре"],"answer":["четырнадцать"]},
    {"question":"Как по-английски «пятнадцать»?","variants":["six","two","fifteen","eight"],"answer":["fifteen"]},
    {"question":"Как переводится «fifteen»?","variants":["семнадцать","шесть","пятнадцать","шестнадцать"],"answer":["пятнадцать"]},
    {"question":"Как по-английски «шестнадцать»?","variants":["sixteen","fifteen","nineteen","eighteen"],"answer":["sixteen"]},
    {"question":"Как переводится «sixteen»?","variants":["один","четырнадцать","восемнадцать","шестнадцать"],"answer":["шестнадцать"]},
    {"question":"Как по-английски «семнадцать»?","variants":["six","seventeen","nine","two"],"answer":["seventeen"]},
    {"question":"Как переводится «seventeen»?","variants":["девятнадцать","семнадцать","четырнадцать","двенадцать"],"answer":["семнадцать"]},
    {"question":"Как по-английски «восемнадцать»?","variants":["fourteen","eighteen","twenty","seven"],"answer":["eighteen"]},
    {"question":"Как переводится «eighteen»?","variants":["восемнадцать","тринадцать","одиннадцать","девятнадцать"],"answer":["восемнадцать"]},
    {"question":"Как по-английски «девятнадцать»?","variants":["nineteen","twenty","six","seventeen"],"answer":["nineteen"]},
    {"question":"Как переводится «nineteen»?","variants":["пять","два","тринадцать","девятнадцать"],"answer":["девятнадцать"]},
    {"question":"Как по-английски «двадцать»?","variants":["fourteen","twenty","four","five"],"answer":["twenty"]},
    {"question":"Как переводится «twenty»?","variants":["шесть","восемь","двадцать","три"],"answer":["двадцать"]},
    {"question":"Как по-английски «красный»?","variants":["brown","red","white","black"],"answer":["red"]},
    {"question":"Как переводится «red»?","variants":["красный","синий","чёрный","жёлтый"],"answer":["красный"]},
    {"question":"Как по-английски «жёлтый»?","variants":["orange","grey","yellow","pink"],"answer":["yellow"]},
    {"question":"Как переводится «yellow»?","variants":["жёлтый","зелёный","розовый","серый"],"answer":["жёлтый"]},
    {"question":"Как по-английски «зелёный»?","variants":["pink","blue","white","green"],"answer":["green"]},
    {"question":"Как переводится «green»?","variants":["зелёный","жёлтый","синий","оранжевый"],"answer":["зелёный"]},
    {"question":"Как по-английски «синий»?","variants":["pink","blue","grey","red"],"answer":["blue"]},
    {"question":"Как переводится «blue»?","variants":["зелёный","оранжевый","синий","фиолетовый"],"answer":["синий"]},
    {"question":"Как по-английски «чёрный»?","variants":["red","black","grey","pink"],"answer":["black"]},
    {"question":"Как переводится «black»?","variants":["чёрный","оранжевый","жёлтый","белый"],"answer":["чёрный"]},
    {"question":"Как по-английски «белый»?","variants":["purple","orange","green","white"],"answer":["white"]},
    {"question":"Как переводится «white»?","variants":["чёрный","коричневый","оранжевый","белый"],"answer":["белый"]},
    {"question":"Как по-английски «серый»?","variants":["black","grey","green","brown"],"answer":["grey"]},
    {"question":"Как переводится «grey»?","variants":["розовый","красный","серый","синий"],"answer":["серый"]},
    {"question":"Как по-английски «коричневый»?","variants":["black","yellow","brown","orange"],"answer":["brown"]},
    {"question":"Как переводится «brown»?","variants":["розовый","белый","коричневый","оранжевый"],"answer":["коричневый"]},
    {"question":"Как по-английски «розовый»?","variants":["green","yellow","pink","brown"],"answer":["pink"]},
    {"question":"Как переводится «pink»?","variants":["серый","синий","розовый","коричневый"],"answer":["розовый"]},
    {"question":"Как по-английски «оранжевый»?","variants":["pink","blue","grey","orange"],"answer":["orange"]},
    {"question":"Как переводится «orange»?","variants":["синий","белый","оранжевый","розовый"],"answer":["оранжевый"]},
    {"question":"Как по-английски «фиолетовый»?","variants":["purple","yellow","brown","green"],"answer":["purple"]},
    {"question":"Как переводится «purple»?","variants":["фиолетовый","чёрный","белый","красный"],"answer":["фиолетовый"]},
    {"question":"Выбери число 1","variants":["eight","one","eighteen","sixteen"],"answer":["one"]},
    {"question":"Выбери число 2","variants":["nine","eighteen","fourteen","two"],"answer":["two"]},
    {"question":"Выбери число 3","variants":["nineteen","eight","fifteen","three"],"answer":["three"]},
    {"question":"Выбери число 4","variants":["six","eleven","four","five"],"answer":["four"]},
    {"question":"Выбери число 5","variants":["five","six","twenty","eighteen"],"answer":["five"]},
    {"question":"Выбери число 6","variants":["eighteen","one","two","six"],"answer":["six"]},
    {"question":"Выбери число 7","variants":["five","six","eight","seven"],"answer":["seven"]},
    {"question":"Выбери число 8","variants":["thirteen","eleven","two","eight"],"answer":["eight"]},
    {"question":"Выбери число 9","variants":["eight","nine","eighteen","nineteen"],"answer":["nine"]},
    {"question":"Выбери число 10","variants":["twelve","ten","fifteen","four"],"answer":["ten"]},
    {"question":"Выбери число 11","variants":["nineteen","eleven","eight","one"],"answer":["eleven"]},
    {"question":"Выбери число 12","variants":["nine","eighteen","twelve","four"],"answer":["twelve"]},
    {"question":"Выбери число 13","variants":["thirteen","ten","fifteen","one"],"answer":["thirteen"]},
    {"question":"Выбери число 14","variants":["ten","nineteen","fourteen","eleven"],"answer":["fourteen"]},
    {"question":"Выбери число 15","variants":["fifteen","eight","fourteen","nine"],"answer":["fifteen"]},
    {"question":"Выбери число 16","variants":["nine","two","sixteen","ten"],"answer":["sixteen"]},
    {"question":"Выбери число 17","variants":["seventeen","twenty","fourteen","nine"],"answer":["seventeen"]},
    {"question":"Выбери число 18","variants":["seventeen","eighteen","fifteen","two"],"answer":["eighteen"]},
    {"question":"Выбери число 19","variants":["nine","nineteen","sixteen","thirteen"],"answer":["nineteen"]},
    {"question":"Выбери число 20","variants":["nineteen","twenty","five","thirteen"],"answer":["twenty"]},
    {"question":"Как по-английски «Привет»?","variants":["Good morning","Hello","My name is","Thank you"],"answer":["Hello"]},
    {"question":"Как по-английски «До свидания»?","variants":["My name is","Good morning","Goodbye","Please"],"answer":["Goodbye"]},
    {"question":"Как по-английски «Доброе утро»?","variants":["My name is","Good morning","Good night","Yes"],"answer":["Good morning"]},
    {"question":"Как по-английски «Спокойной ночи»?","variants":["Good night","Yes","Hello","Thank you"],"answer":["Good night"]},
    {"question":"Как по-английски «Спасибо»?","variants":["Good night","My name is","Thank you","How are you?"],"answer":["Thank you"]},
    {"question":"Как по-английски «Пожалуйста»?","variants":["How are you?","Good night","Goodbye","Please"],"answer":["Please"]},
    {"question":"Как по-английски «Да»?","variants":["Hello","Please","Yes","Goodbye"],"answer":["Yes"]},
    {"question":"Как по-английски «Нет»?","variants":["My name is","Yes","No","Please"],"answer":["No"]},
    {"question":"Как по-английски «Как дела?»?","variants":["Please","Yes","Good night","How are you?"],"answer":["How are you?"]},
    {"question":"Как по-английски «Меня зовут»?","variants":["No","My name is","How are you?","Yes"],"answer":["My name is"]},
  ]
};
