export default {
  "title": "Моя семья",
  "questions": [
    {"question":"Как по-английски «мама»?","variants":["mother","daddy","uncle","happy"],"answer":["mother"]},
    {"question":"Как переводится «mother»?","variants":["мама (ласково)","мама","сосед","родители"],"answer":["мама"]},
    {"question":"Как по-английски «папа»?","variants":["cousin","like","father","have"],"answer":["father"]},
    {"question":"Как переводится «father»?","variants":["брат","папа","родители","сосед"],"answer":["папа"]},
    {"question":"Как по-английски «мама (ласково)»?","variants":["love","grandpa","mummy","happy"],"answer":["mummy"]},
    {"question":"Как переводится «mummy»?","variants":["иметь","семья","мама (ласково)","дедушка"],"answer":["мама (ласково)"]},
    {"question":"Как по-английски «папа (ласково)»?","variants":["grandma","mummy","daddy","a dad"],"answer":["daddy"]},
    {"question":"Как переводится «daddy»?","variants":["папа (ласково)","любить","бабушка","дети"],"answer":["папа (ласково)"]},
    {"question":"Как по-английски «сестра»?","variants":["grandad","like","daughter","sister"],"answer":["sister"]},
    {"question":"Как переводится «sister»?","variants":["сосед","сын","дедушка","сестра"],"answer":["сестра"]},
    {"question":"Как по-английски «брат»?","variants":["aunt","brother","granny","uncle"],"answer":["brother"]},
    {"question":"Как переводится «brother»?","variants":["брат","дядя","мама (ласково)","дедушка"],"answer":["брат"]},
    {"question":"Как по-английски «бабушка»?","variants":["grandma","uncle","happy","children"],"answer":["grandma"]},
    {"question":"Как переводится «grandma»?","variants":["папа (ласково)","бабушка","дедушка","иметь"],"answer":["бабушка"]},
    {"question":"Как по-английски «дедушка»?","variants":["a dad","family","grandpa","have"],"answer":["grandpa"]},
    {"question":"Как переводится «grandpa»?","variants":["счастливый","сын","дедушка","папа (ласково)"],"answer":["дедушка"]},
    {"question":"Как по-английски «тётя»?","variants":["cousin","happy","aunt","a twin"],"answer":["aunt"]},
    {"question":"Как переводится «aunt»?","variants":["иметь","тётя","дедушка","двоюродный брат/сестра"],"answer":["тётя"]},
    {"question":"Как по-английски «дядя»?","variants":["a neighbour","uncle","grandpa","daughter"],"answer":["uncle"]},
    {"question":"Как переводится «uncle»?","variants":["дядя","малыш","сын","дедуля"],"answer":["дядя"]},
    {"question":"Как по-английски «двоюродный брат/сестра»?","variants":["mother","cousin","father","grandpa"],"answer":["cousin"]},
    {"question":"Как переводится «cousin»?","variants":["папа (ласково)","двоюродный брат/сестра","брат","дядя"],"answer":["двоюродный брат/сестра"]},
    {"question":"Как по-английски «малыш»?","variants":["like","parents","grandad","baby"],"answer":["baby"]},
    {"question":"Как переводится «baby»?","variants":["бабуля","друг","малыш","сын"],"answer":["малыш"]},
    {"question":"Как по-английски «сын»?","variants":["son","grandpa","aunt","grandmother"],"answer":["son"]},
    {"question":"Как переводится «son»?","variants":["бабушка","сын","дочь","дядя"],"answer":["сын"]},
    {"question":"Как по-английски «дочь»?","variants":["grandfather","grandpa","grandmother","daughter"],"answer":["daughter"]},
    {"question":"Как переводится «daughter»?","variants":["дети","дочь","мама (ласково)","брат"],"answer":["дочь"]},
    {"question":"Как по-английски «семья»?","variants":["grandma","like","grandpa","family"],"answer":["family"]},
    {"question":"Как переводится «family»?","variants":["семья","иметь","любить","родители"],"answer":["семья"]},
    {"question":"Как по-английски «родители»?","variants":["parents","children","a neighbour","a mum"],"answer":["parents"]},
    {"question":"Как переводится «parents»?","variants":["родители","дедуля","иметь","счастливый"],"answer":["родители"]},
    {"question":"Как по-английски «дети»?","variants":["brother","family","uncle","children"],"answer":["children"]},
    {"question":"Как переводится «children»?","variants":["дети","близнец","друг","брат"],"answer":["дети"]},
    {"question":"Как переводится «grandmother»?","variants":["иметь","дети","бабушка","дядя"],"answer":["бабушка"]},
    {"question":"Как переводится «grandfather»?","variants":["сын","папа","семья","дедушка"],"answer":["дедушка"]},
    {"question":"Как по-английски «бабуля»?","variants":["love","granny","baby","family"],"answer":["granny"]},
    {"question":"Как переводится «granny»?","variants":["сын","брат","бабуля","папа"],"answer":["бабуля"]},
    {"question":"Как по-английски «дедуля»?","variants":["mummy","uncle","grandpa","grandad"],"answer":["grandad"]},
    {"question":"Как переводится «grandad»?","variants":["папа","дедуля","мама","дядя"],"answer":["дедуля"]},
    {"question":"Как переводится «a mum»?","variants":["друг","мама","дедуля","родители"],"answer":["мама"]},
    {"question":"Как переводится «a dad»?","variants":["папа","друг","мама","сын"],"answer":["папа"]},
    {"question":"Как по-английски «близнец»?","variants":["a twin","mummy","grandmother","like"],"answer":["a twin"]},
    {"question":"Как переводится «a twin»?","variants":["папа","бабушка","двоюродный брат/сестра","близнец"],"answer":["близнец"]},
    {"question":"Как по-английски «друг»?","variants":["a friend","cousin","grandmother","mother"],"answer":["a friend"]},
    {"question":"Как переводится «a friend»?","variants":["мама (ласково)","иметь","друг","близнец"],"answer":["друг"]},
    {"question":"Как по-английски «сосед»?","variants":["a neighbour","parents","a friend","a mum"],"answer":["a neighbour"]},
    {"question":"Как переводится «a neighbour»?","variants":["сын","дедуля","сосед","дедушка"],"answer":["сосед"]},
    {"question":"Как по-английски «любить»?","variants":["son","love","sister","grandpa"],"answer":["love"]},
    {"question":"Как переводится «love»?","variants":["любить","папа","дети","родители"],"answer":["любить"]},
    {"question":"Как по-английски «иметь»?","variants":["have","a neighbour","family","grandpa"],"answer":["have"]},
    {"question":"Как переводится «have»?","variants":["иметь","дедушка","бабушка","дедушка"],"answer":["иметь"]},
    {"question":"Как по-английски «нравиться»?","variants":["uncle","like","a mum","father"],"answer":["like"]},
    {"question":"Как переводится «like»?","variants":["нравиться","любить","дедушка","бабуля"],"answer":["нравиться"]},
    {"question":"Как по-английски «счастливый»?","variants":["a friend","granny","happy","mummy"],"answer":["happy"]},
    {"question":"Как переводится «happy»?","variants":["мама","счастливый","родители","бабуля"],"answer":["счастливый"]},
    {"question":"Как по-английски «мой»?","variants":["his","I","my","they"],"answer":["my"]},
    {"question":"Как переводится «my»?","variants":["мы","их","мой","наш"],"answer":["мой"]},
    {"question":"Как по-английски «твой»?","variants":["your","he","I","her"],"answer":["your"]},
    {"question":"Как переводится «your»?","variants":["он","они","мы","твой"],"answer":["твой"]},
    {"question":"Как по-английски «его»?","variants":["his","she","I","our"],"answer":["his"]},
    {"question":"Как переводится «his»?","variants":["мой","её","они","его"],"answer":["его"]},
    {"question":"Как по-английски «её»?","variants":["her","she","his","their"],"answer":["her"]},
    {"question":"Как переводится «her»?","variants":["ты","она","её","мой"],"answer":["её"]},
    {"question":"Как по-английски «наш»?","variants":["their","you","we","our"],"answer":["our"]},
    {"question":"Как переводится «our»?","variants":["её","его","они","наш"],"answer":["наш"]},
    {"question":"Как по-английски «их»?","variants":["we","their","he","her"],"answer":["their"]},
    {"question":"Как переводится «their»?","variants":["он","её","мы","их"],"answer":["их"]},
    {"question":"Как по-английски «я»?","variants":["their","his","we","I"],"answer":["I"]},
    {"question":"Как переводится «I»?","variants":["они","я","мой","их"],"answer":["я"]},
    {"question":"Как по-английски «он»?","variants":["we","he","they","your"],"answer":["he"]},
    {"question":"Как переводится «he»?","variants":["его","мой","я","он"],"answer":["он"]},
    {"question":"Как по-английски «она»?","variants":["they","she","our","you"],"answer":["she"]},
    {"question":"Как переводится «she»?","variants":["наш","она","он","твой"],"answer":["она"]},
    {"question":"Как по-английски «мы»?","variants":["my","we","they","he"],"answer":["we"]},
    {"question":"Как переводится «we»?","variants":["она","мы","его","они"],"answer":["мы"]},
    {"question":"Как по-английски «они»?","variants":["he","they","my","you"],"answer":["they"]},
    {"question":"Как переводится «they»?","variants":["наш","их","они","твой"],"answer":["они"]},
    {"question":"Как по-английски «ты»?","variants":["I","you","they","my"],"answer":["you"]},
    {"question":"Как переводится «you»?","variants":["их","ты","твой","наш"],"answer":["ты"]},
  ]
};
