export default {
  "title": "Еда и напитки",
  "questions": [
    {"question":"Как по-английски «хлеб»?","variants":["cake","supper","bread","apple"],"answer":["bread"]},
    {"question":"Как переводится «bread»?","variants":["хлеб","суп","яблоко","морковь"],"answer":["хлеб"]},
    {"question":"Как по-английски «молоко»?","variants":["milk","meat","juice","tomato"],"answer":["milk"]},
    {"question":"Как переводится «milk»?","variants":["молоко","яйца","печенье","лимон"],"answer":["молоко"]},
    {"question":"Как по-английски «торт»?","variants":["cake","biscuit","apple","bread"],"answer":["cake"]},
    {"question":"Как переводится «cake»?","variants":["торт","завтрак","морковь","обед"],"answer":["торт"]},
    {"question":"Как по-английски «рыба»?","variants":["rice","breakfast","cake","fish"],"answer":["fish"]},
    {"question":"Как переводится «fish»?","variants":["рыба","салат","вода","суп"],"answer":["рыба"]},
    {"question":"Как по-английски «мясо»?","variants":["potato","meat","lemon","sugar"],"answer":["meat"]},
    {"question":"Как переводится «meat»?","variants":["рис","мясо","суп","кофе"],"answer":["мясо"]},
    {"question":"Как по-английски «рис»?","variants":["milk","rice","cheese","sandwich"],"answer":["rice"]},
    {"question":"Как переводится «rice»?","variants":["лимон","рис","апельсин","картофель"],"answer":["рис"]},
    {"question":"Как по-английски «сыр»?","variants":["rice","cake","cheese","water"],"answer":["cheese"]},
    {"question":"Как переводится «cheese»?","variants":["сыр","ужин","вода","обед"],"answer":["сыр"]},
    {"question":"Как по-английски «яйца»?","variants":["burger","eggs","salad","sandwich"],"answer":["eggs"]},
    {"question":"Как переводится «eggs»?","variants":["сок","сахар","мясо","яйца"],"answer":["яйца"]},
    {"question":"Как по-английски «сок»?","variants":["soup","juice","sandwich","potato"],"answer":["juice"]},
    {"question":"Как переводится «juice»?","variants":["сок","чай","бутерброд","завтрак"],"answer":["сок"]},
    {"question":"Как по-английски «чай»?","variants":["supper","salad","tea","juice"],"answer":["tea"]},
    {"question":"Как переводится «tea»?","variants":["суп","молоко","мясо","чай"],"answer":["чай"]},
    {"question":"Как по-английски «вода»?","variants":["burger","water","supper","tea"],"answer":["water"]},
    {"question":"Как переводится «water»?","variants":["завтрак","яйца","вода","помидор"],"answer":["вода"]},
    {"question":"Как по-английски «кофе»?","variants":["sugar","coffee","water","tomato"],"answer":["coffee"]},
    {"question":"Как переводится «coffee»?","variants":["рис","суп","сахар","кофе"],"answer":["кофе"]},
    {"question":"Как по-английски «мороженое»?","variants":["ice cream","juice","carrot","sandwich"],"answer":["ice cream"]},
    {"question":"Как переводится «ice cream»?","variants":["мороженое","кофе","картофель","печенье"],"answer":["мороженое"]},
    {"question":"Как по-английски «печенье»?","variants":["coffee","pizza","biscuit","fish"],"answer":["biscuit"]},
    {"question":"Как переводится «biscuit»?","variants":["рис","банан","печенье","морковь"],"answer":["печенье"]},
    {"question":"Как по-английски «яблоко»?","variants":["orange","water","apple","banana"],"answer":["apple"]},
    {"question":"Как переводится «apple»?","variants":["сахар","ужин","пицца","яблоко"],"answer":["яблоко"]},
    {"question":"Как по-английски «банан»?","variants":["banana","pizza","milk","fish"],"answer":["banana"]},
    {"question":"Как переводится «banana»?","variants":["яйца","завтрак","сыр","банан"],"answer":["банан"]},
    {"question":"Как по-английски «апельсин»?","variants":["tomato","orange","potato","bread"],"answer":["orange"]},
    {"question":"Как переводится «orange»?","variants":["апельсин","завтрак","печенье","молоко"],"answer":["апельсин"]},
    {"question":"Как по-английски «лимон»?","variants":["breakfast","lemon","cheese","tea"],"answer":["lemon"]},
    {"question":"Как переводится «lemon»?","variants":["рис","вода","лимон","мясо"],"answer":["лимон"]},
    {"question":"Как по-английски «конфета»?","variants":["tomato","candy","eggs","tea"],"answer":["candy"]},
    {"question":"Как переводится «candy»?","variants":["картофель","рис","конфета","завтрак"],"answer":["конфета"]},
    {"question":"Как по-английски «суп»?","variants":["soup","milk","apple","tea"],"answer":["soup"]},
    {"question":"Как переводится «soup»?","variants":["завтрак","апельсин","кофе","суп"],"answer":["суп"]},
    {"question":"Как по-английски «пицца»?","variants":["juice","bread","pizza","biscuit"],"answer":["pizza"]},
    {"question":"Как переводится «pizza»?","variants":["бургер","банан","пицца","салат"],"answer":["пицца"]},
    {"question":"Как по-английски «бургер»?","variants":["tomato","carrot","burger","sandwich"],"answer":["burger"]},
    {"question":"Как переводится «burger»?","variants":["ужин","рыба","молоко","бургер"],"answer":["бургер"]},
    {"question":"Как по-английски «бутерброд»?","variants":["tomato","milk","sandwich","water"],"answer":["sandwich"]},
    {"question":"Как переводится «sandwich»?","variants":["банан","ужин","чай","бутерброд"],"answer":["бутерброд"]},
    {"question":"Как по-английски «сахар»?","variants":["water","cheese","orange","sugar"],"answer":["sugar"]},
    {"question":"Как переводится «sugar»?","variants":["чай","сок","сахар","завтрак"],"answer":["сахар"]},
    {"question":"Как по-английски «картофель»?","variants":["potato","dinner","milk","sandwich"],"answer":["potato"]},
    {"question":"Как переводится «potato»?","variants":["яблоко","ужин","картофель","обед"],"answer":["картофель"]},
    {"question":"Как по-английски «помидор»?","variants":["juice","supper","ice cream","tomato"],"answer":["tomato"]},
    {"question":"Как переводится «tomato»?","variants":["помидор","торт","чай","конфета"],"answer":["помидор"]},
    {"question":"Как по-английски «морковь»?","variants":["cake","potato","meat","carrot"],"answer":["carrot"]},
    {"question":"Как переводится «carrot»?","variants":["морковь","банан","рыба","бургер"],"answer":["морковь"]},
    {"question":"Как по-английски «салат»?","variants":["bread","salad","sugar","meat"],"answer":["salad"]},
    {"question":"Как переводится «salad»?","variants":["помидор","яблоко","сок","салат"],"answer":["салат"]},
    {"question":"Как по-английски «завтрак»?","variants":["supper","soup","breakfast","water"],"answer":["breakfast"]},
    {"question":"Как переводится «breakfast»?","variants":["завтрак","салат","пицца","лимон"],"answer":["завтрак"]},
    {"question":"Как по-английски «обед»?","variants":["coffee","tea","dinner","orange"],"answer":["dinner"]},
    {"question":"Как переводится «dinner»?","variants":["печенье","лимон","обед","яйца"],"answer":["обед"]},
    {"question":"Как по-английски «ужин»?","variants":["cheese","supper","meat","sandwich"],"answer":["supper"]},
    {"question":"Как переводится «supper»?","variants":["яйца","торт","сок","ужин"],"answer":["ужин"]},
  ]
};
