export default {
  "title": "Игрушки, предлоги и глаголы",
  "questions": [
    {"question":"Как по-английски «игрушка»?","variants":["a scooter","a kite","a toy","a boat"],"answer":["a toy"]},
    {"question":"Как переводится «a toy»?","variants":["игрушка","робот","самокат","воздушный змей"],"answer":["игрушка"]},
    {"question":"Как по-английски «мяч»?","variants":["a ball","a train","a drum","a car"],"answer":["a ball"]},
    {"question":"Как переводится «a ball»?","variants":["мяч","робот","самокат","барабан"],"answer":["мяч"]},
    {"question":"Как по-английски «кукла»?","variants":["a train","a kite","a teddy bear","a doll"],"answer":["a doll"]},
    {"question":"Как переводится «a doll»?","variants":["плюшевый мишка","кукла","самокат","робот"],"answer":["кукла"]},
    {"question":"Как по-английски «поезд»?","variants":["a puzzle","a bike","a train","a ship"],"answer":["a train"]},
    {"question":"Как переводится «a train»?","variants":["игрушка","поезд","воздушный змей","самокат"],"answer":["поезд"]},
    {"question":"Как по-английски «машина»?","variants":["a car","a train","a drum","a plane"],"answer":["a car"]},
    {"question":"Как переводится «a car»?","variants":["лодка","корабль","велосипед","машина"],"answer":["машина"]},
    {"question":"Как по-английски «самолёт»?","variants":["a scooter","a plane","a car","a puzzle"],"answer":["a plane"]},
    {"question":"Как переводится «a plane»?","variants":["самолёт","корабль","кукла","пазл"],"answer":["самолёт"]},
    {"question":"Как по-английски «лодка»?","variants":["a train","a plane","a boat","a bike"],"answer":["a boat"]},
    {"question":"Как переводится «a boat»?","variants":["барабан","воздушный змей","лодка","плюшевый мишка"],"answer":["лодка"]},
    {"question":"Как по-английски «воздушный змей»?","variants":["a robot","a train","a kite","a teddy bear"],"answer":["a kite"]},
    {"question":"Как переводится «a kite»?","variants":["самокат","самолёт","кукла","воздушный змей"],"answer":["воздушный змей"]},
    {"question":"Как по-английски «плюшевый мишка»?","variants":["a puzzle","a ball","a plane","a teddy bear"],"answer":["a teddy bear"]},
    {"question":"Как переводится «a teddy bear»?","variants":["плюшевый мишка","самолёт","пазл","мяч"],"answer":["плюшевый мишка"]},
    {"question":"Как по-английски «робот»?","variants":["a scooter","a robot","a doll","a drum"],"answer":["a robot"]},
    {"question":"Как переводится «a robot»?","variants":["самолёт","самокат","робот","машина"],"answer":["робот"]},
    {"question":"Как по-английски «пазл»?","variants":["a bike","a puzzle","a kite","a plane"],"answer":["a puzzle"]},
    {"question":"Как переводится «a puzzle»?","variants":["плюшевый мишка","игрушка","пазл","робот"],"answer":["пазл"]},
    {"question":"Как по-английски «корабль»?","variants":["a plane","a boat","a doll","a ship"],"answer":["a ship"]},
    {"question":"Как переводится «a ship»?","variants":["плюшевый мишка","велосипед","кукла","корабль"],"answer":["корабль"]},
    {"question":"Как по-английски «барабан»?","variants":["a ball","a drum","a doll","a robot"],"answer":["a drum"]},
    {"question":"Как переводится «a drum»?","variants":["самолёт","велосипед","барабан","лодка"],"answer":["барабан"]},
    {"question":"Как по-английски «велосипед»?","variants":["a train","a robot","a bike","a ship"],"answer":["a bike"]},
    {"question":"Как переводится «a bike»?","variants":["робот","велосипед","воздушный змей","поезд"],"answer":["велосипед"]},
    {"question":"Как по-английски «самокат»?","variants":["a plane","a scooter","a kite","a bike"],"answer":["a scooter"]},
    {"question":"Как переводится «a scooter»?","variants":["самокат","плюшевый мишка","кукла","велосипед"],"answer":["самокат"]},
    {"question":"Как по-английски «в»?","variants":["behind","near","in","under"],"answer":["in"]},
    {"question":"Как переводится «in»?","variants":["между","рядом с","перед","в"],"answer":["в"]},
    {"question":"Как по-английски «на»?","variants":["next to","on","between","near"],"answer":["on"]},
    {"question":"Как переводится «on»?","variants":["на","в","за","между"],"answer":["на"]},
    {"question":"Как по-английски «под»?","variants":["under","near","behind","next to"],"answer":["under"]},
    {"question":"Как переводится «under»?","variants":["под","перед","на","рядом с"],"answer":["под"]},
    {"question":"Как по-английски «около»?","variants":["next to","in","near","on"],"answer":["near"]},
    {"question":"Как переводится «near»?","variants":["под","на","около","между"],"answer":["около"]},
    {"question":"Как по-английски «за»?","variants":["between","under","in front of","behind"],"answer":["behind"]},
    {"question":"Как переводится «behind»?","variants":["за","под","около","между"],"answer":["за"]},
    {"question":"Как по-английски «перед»?","variants":["in front of","in","between","under"],"answer":["in front of"]},
    {"question":"Как переводится «in front of»?","variants":["рядом с","между","перед","на"],"answer":["перед"]},
    {"question":"Как по-английски «рядом с»?","variants":["in front of","next to","in","between"],"answer":["next to"]},
    {"question":"Как переводится «next to»?","variants":["за","рядом с","на","перед"],"answer":["рядом с"]},
    {"question":"Как по-английски «между»?","variants":["between","next to","behind","near"],"answer":["between"]},
    {"question":"Как переводится «between»?","variants":["между","около","под","на"],"answer":["между"]},
    {"question":"Как по-английски «играть»?","variants":["jump","swim","climb","play"],"answer":["play"]},
    {"question":"Как переводится «play»?","variants":["плавать","играть","прыгать","лазать"],"answer":["играть"]},
    {"question":"Как по-английски «прыгать»?","variants":["dance","jump","fly","run"],"answer":["jump"]},
    {"question":"Как переводится «jump»?","variants":["летать","прыгать","бегать","плавать"],"answer":["прыгать"]},
    {"question":"Как по-английски «бегать»?","variants":["jump","climb","fly","run"],"answer":["run"]},
    {"question":"Как переводится «run»?","variants":["играть","петь","танцевать","бегать"],"answer":["бегать"]},
    {"question":"Как по-английски «плавать»?","variants":["climb","play","swim","jump"],"answer":["swim"]},
    {"question":"Как переводится «swim»?","variants":["лазать","плавать","прыгать","играть"],"answer":["плавать"]},
    {"question":"Как по-английски «летать»?","variants":["fly","sing","play","climb"],"answer":["fly"]},
    {"question":"Как переводится «fly»?","variants":["танцевать","петь","летать","играть"],"answer":["летать"]},
    {"question":"Как по-английски «лазать»?","variants":["dance","jump","climb","play"],"answer":["climb"]},
    {"question":"Как переводится «climb»?","variants":["лазать","петь","играть","летать"],"answer":["лазать"]},
    {"question":"Как по-английски «танцевать»?","variants":["run","dance","jump","swim"],"answer":["dance"]},
    {"question":"Как переводится «dance»?","variants":["лазать","летать","бегать","танцевать"],"answer":["танцевать"]},
    {"question":"Как по-английски «петь»?","variants":["run","dance","sing","swim"],"answer":["sing"]},
    {"question":"Как переводится «sing»?","variants":["летать","играть","танцевать","петь"],"answer":["петь"]},
  ]
};
