export default {
  "title": "Животные и части тела",
  "questions": [
    {"question":"Как по-английски «кошка»?","variants":["a frog","a monkey","a cat","a hen"],"answer":["a cat"]},
    {"question":"Как переводится «a cat»?","variants":["кит","овца","кошка","лягушка"],"answer":["кошка"]},
    {"question":"Как по-английски «собака»?","variants":["a sheep","a wolf","a bear","a dog"],"answer":["a dog"]},
    {"question":"Как переводится «a dog»?","variants":["курица","птица","лошадь","собака"],"answer":["собака"]},
    {"question":"Как по-английски «медведь»?","variants":["a frog","a whale","a cow","a bear"],"answer":["a bear"]},
    {"question":"Как переводится «a bear»?","variants":["птица","медведь","кит","лев"],"answer":["медведь"]},
    {"question":"Как по-английски «заяц»?","variants":["a hare","a wolf","a monkey","a frog"],"answer":["a hare"]},
    {"question":"Как переводится «a hare»?","variants":["курица","дельфин","кит","заяц"],"answer":["заяц"]},
    {"question":"Как по-английски «кролик»?","variants":["a bear","a bird","a tiger","a rabbit"],"answer":["a rabbit"]},
    {"question":"Как переводится «a rabbit»?","variants":["кошка","лошадь","змея","кролик"],"answer":["кролик"]},
    {"question":"Как по-английски «лиса»?","variants":["a mouse","a cow","a frog","a fox"],"answer":["a fox"]},
    {"question":"Как переводится «a fox»?","variants":["лиса","дельфин","овца","кит"],"answer":["лиса"]},
    {"question":"Как по-английски «волк»?","variants":["a tiger","a bird","a wolf","a sheep"],"answer":["a wolf"]},
    {"question":"Как переводится «a wolf»?","variants":["лев","птица","волк","кролик"],"answer":["волк"]},
    {"question":"Как по-английски «тигр»?","variants":["a tiger","a lion","a cat","a fox"],"answer":["a tiger"]},
    {"question":"Как переводится «a tiger»?","variants":["кит","обезьяна","заяц","тигр"],"answer":["тигр"]},
    {"question":"Как по-английски «лев»?","variants":["a cat","a dog","an elephant","a lion"],"answer":["a lion"]},
    {"question":"Как переводится «a lion»?","variants":["дельфин","змея","лев","собака"],"answer":["лев"]},
    {"question":"Как по-английски «слон»?","variants":["a pig","a cat","a crocodile","an elephant"],"answer":["an elephant"]},
    {"question":"Как переводится «an elephant»?","variants":["дельфин","корова","тигр","слон"],"answer":["слон"]},
    {"question":"Как по-английски «обезьяна»?","variants":["a whale","a hen","a parrot","a monkey"],"answer":["a monkey"]},
    {"question":"Как переводится «a monkey»?","variants":["овца","обезьяна","дельфин","рыба"],"answer":["обезьяна"]},
    {"question":"Как по-английски «мышь»?","variants":["an elephant","a mouse","a tiger","a bird"],"answer":["a mouse"]},
    {"question":"Как переводится «a mouse»?","variants":["лиса","мышь","утка","тигр"],"answer":["мышь"]},
    {"question":"Как по-английски «черепаха»?","variants":["a bear","a hare","a horse","a tortoise"],"answer":["a tortoise"]},
    {"question":"Как переводится «a tortoise»?","variants":["курица","черепаха","кит","тигр"],"answer":["черепаха"]},
    {"question":"Как по-английски «попугай»?","variants":["a parrot","a wolf","a bear","a snake"],"answer":["a parrot"]},
    {"question":"Как переводится «a parrot»?","variants":["медведь","лошадь","дельфин","попугай"],"answer":["попугай"]},
    {"question":"Как по-английски «курица»?","variants":["a tiger","a hen","an elephant","a parrot"],"answer":["a hen"]},
    {"question":"Как переводится «a hen»?","variants":["птица","курица","слон","кролик"],"answer":["курица"]},
    {"question":"Как по-английски «лягушка»?","variants":["a crocodile","a snake","a frog","a tiger"],"answer":["a frog"]},
    {"question":"Как переводится «a frog»?","variants":["лягушка","змея","курица","черепаха"],"answer":["лягушка"]},
    {"question":"Как по-английски «рыба»?","variants":["a pig","a whale","a cat","a fish"],"answer":["a fish"]},
    {"question":"Как переводится «a fish»?","variants":["рыба","собака","лягушка","медведь"],"answer":["рыба"]},
    {"question":"Как по-английски «лошадь»?","variants":["a snake","a parrot","a tiger","a horse"],"answer":["a horse"]},
    {"question":"Как переводится «a horse»?","variants":["слон","кролик","волк","лошадь"],"answer":["лошадь"]},
    {"question":"Как по-английски «корова»?","variants":["a cow","a frog","a snake","a horse"],"answer":["a cow"]},
    {"question":"Как переводится «a cow»?","variants":["утка","корова","волк","мышь"],"answer":["корова"]},
    {"question":"Как по-английски «овца»?","variants":["a sheep","a monkey","a hare","a mouse"],"answer":["a sheep"]},
    {"question":"Как переводится «a sheep»?","variants":["мышь","овца","заяц","корова"],"answer":["овца"]},
    {"question":"Как по-английски «свинья»?","variants":["a tortoise","a dog","an elephant","a pig"],"answer":["a pig"]},
    {"question":"Как переводится «a pig»?","variants":["крокодил","лошадь","свинья","тигр"],"answer":["свинья"]},
    {"question":"Как по-английски «утка»?","variants":["a bird","a hen","a sheep","a duck"],"answer":["a duck"]},
    {"question":"Как переводится «a duck»?","variants":["волк","свинья","дельфин","утка"],"answer":["утка"]},
    {"question":"Как по-английски «птица»?","variants":["a frog","a hen","a bird","an elephant"],"answer":["a bird"]},
    {"question":"Как переводится «a bird»?","variants":["заяц","кошка","обезьяна","птица"],"answer":["птица"]},
    {"question":"Как по-английски «крокодил»?","variants":["a crocodile","a rabbit","a duck","a snake"],"answer":["a crocodile"]},
    {"question":"Как переводится «a crocodile»?","variants":["крокодил","утка","дельфин","кролик"],"answer":["крокодил"]},
    {"question":"Как по-английски «змея»?","variants":["a snake","a parrot","a wolf","a hare"],"answer":["a snake"]},
    {"question":"Как переводится «a snake»?","variants":["волк","кит","змея","свинья"],"answer":["змея"]},
    {"question":"Как по-английски «дельфин»?","variants":["a whale","a dolphin","a fox","a bear"],"answer":["a dolphin"]},
    {"question":"Как переводится «a dolphin»?","variants":["лошадь","дельфин","медведь","змея"],"answer":["дельфин"]},
    {"question":"Как по-английски «кит»?","variants":["a hare","a whale","a bear","a wolf"],"answer":["a whale"]},
    {"question":"Как переводится «a whale»?","variants":["кролик","лошадь","обезьяна","кит"],"answer":["кит"]},
    {"question":"Как по-английски «хвост»?","variants":["a nose","a head","a tail","eyes"],"answer":["a tail"]},
    {"question":"Как переводится «a tail»?","variants":["хвост","рука","рот","ухо"],"answer":["хвост"]},
    {"question":"Как по-английски «глаза»?","variants":["a nose","an ear","eyes","a mouth"],"answer":["eyes"]},
    {"question":"Как переводится «eyes»?","variants":["нос","глаза","хвост","рот"],"answer":["глаза"]},
    {"question":"Как по-английски «ухо»?","variants":["a hand","a mouth","eyes","an ear"],"answer":["an ear"]},
    {"question":"Как переводится «an ear»?","variants":["ухо","голова","рот","нога"],"answer":["ухо"]},
    {"question":"Как по-английски «нос»?","variants":["a mouth","a nose","eyes","a head"],"answer":["a nose"]},
    {"question":"Как переводится «a nose»?","variants":["рука","ухо","нос","голова"],"answer":["нос"]},
    {"question":"Как по-английски «рот»?","variants":["an ear","a leg","a mouth","a head"],"answer":["a mouth"]},
    {"question":"Как переводится «a mouth»?","variants":["рот","рука","глаза","голова"],"answer":["рот"]},
    {"question":"Как по-английски «нога»?","variants":["a head","a leg","eyes","a hand"],"answer":["a leg"]},
    {"question":"Как переводится «a leg»?","variants":["нога","рот","глаза","голова"],"answer":["нога"]},
    {"question":"Как по-английски «рука»?","variants":["an ear","a leg","a hand","a tail"],"answer":["a hand"]},
    {"question":"Как переводится «a hand»?","variants":["рука","голова","рот","ухо"],"answer":["рука"]},
    {"question":"Как по-английски «голова»?","variants":["a head","a mouth","a tail","an ear"],"answer":["a head"]},
    {"question":"Как переводится «a head»?","variants":["рот","глаза","голова","нога"],"answer":["голова"]},
  ]
};
