export default {
  "title": "Дом, комнаты и мебель",
  "questions": [
    {"question":"Как по-английски «дом»?","variants":["a carpet","a curtain","a house","a picture"],"answer":["a house"]},
    {"question":"Как переводится «a house»?","variants":["дом","одеяло","ванная","прихожая"],"answer":["дом"]},
    {"question":"Как по-английски «комната»?","variants":["a room","a curtain","a floor","a blanket"],"answer":["a room"]},
    {"question":"Как переводится «a room»?","variants":["диван","комната","раковина","дом"],"answer":["комната"]},
    {"question":"Как по-английски «окно»?","variants":["a picture","a mirror","a window","a bedroom"],"answer":["a window"]},
    {"question":"Как переводится «a window»?","variants":["прихожая","окно","кресло","крыша"],"answer":["окно"]},
    {"question":"Как по-английски «дверь»?","variants":["a window","a door","a sofa","a bathroom"],"answer":["a door"]},
    {"question":"Как переводится «a door»?","variants":["дверь","пол","зеркало","балкон"],"answer":["дверь"]},
    {"question":"Как по-английски «кровать»?","variants":["a bedroom","an armchair","a bed","a radio"],"answer":["a bed"]},
    {"question":"Как переводится «a bed»?","variants":["окно","кровать","одеяло","часы"],"answer":["кровать"]},
    {"question":"Как по-английски «стол»?","variants":["a bed","a staircase","a clock","a table"],"answer":["a table"]},
    {"question":"Как переводится «a table»?","variants":["прихожая","стол","балкон","кухня"],"answer":["стол"]},
    {"question":"Как по-английски «стул»?","variants":["a chair","a door","a floor","a blanket"],"answer":["a chair"]},
    {"question":"Как переводится «a chair»?","variants":["подушка","гостиная","лампа","стул"],"answer":["стул"]},
    {"question":"Как по-английски «диван»?","variants":["a fridge","a sofa","a bookcase","a carpet"],"answer":["a sofa"]},
    {"question":"Как переводится «a sofa»?","variants":["лампа","телевизор","раковина","диван"],"answer":["диван"]},
    {"question":"Как по-английски «лампа»?","variants":["a blanket","a carpet","a lamp","a picture"],"answer":["a lamp"]},
    {"question":"Как переводится «a lamp»?","variants":["занавеска","лампа","ванная","дверной звонок"],"answer":["лампа"]},
    {"question":"Как по-английски «сад»?","variants":["a hallway","a carpet","a house","a garden"],"answer":["a garden"]},
    {"question":"Как переводится «a garden»?","variants":["книжный шкаф","радио","сад","ванная"],"answer":["сад"]},
    {"question":"Как по-английски «стена»?","variants":["a mirror","a living room","a shower","a wall"],"answer":["a wall"]},
    {"question":"Как переводится «a wall»?","variants":["балкон","сад","комната","стена"],"answer":["стена"]},
    {"question":"Как по-английски «пол»?","variants":["a floor","a computer","a pillow","a living room"],"answer":["a floor"]},
    {"question":"Как переводится «a floor»?","variants":["пол","дом","комната","зеркало"],"answer":["пол"]},
    {"question":"Как по-английски «крыша»?","variants":["a bathroom","a wall","a roof","a TV"],"answer":["a roof"]},
    {"question":"Как переводится «a roof»?","variants":["балкон","комната","пол","крыша"],"answer":["крыша"]},
    {"question":"Как по-английски «кухня»?","variants":["a staircase","an armchair","a kitchen","a clock"],"answer":["a kitchen"]},
    {"question":"Как переводится «a kitchen»?","variants":["стул","стена","кухня","окно"],"answer":["кухня"]},
    {"question":"Как по-английски «спальня»?","variants":["a bedroom","a curtain","a garden","a radio"],"answer":["a bedroom"]},
    {"question":"Как переводится «a bedroom»?","variants":["кресло","спальня","лестница","кухня"],"answer":["спальня"]},
    {"question":"Как по-английски «ванная»?","variants":["a TV","a telephone","a bathroom","a window"],"answer":["a bathroom"]},
    {"question":"Как переводится «a bathroom»?","variants":["шкаф для одежды","ванная","душ","сад"],"answer":["ванная"]},
    {"question":"Как по-английски «гостиная»?","variants":["a shower","a basement","a living room","a roof"],"answer":["a living room"]},
    {"question":"Как переводится «a living room»?","variants":["зеркало","чердак","дом","гостиная"],"answer":["гостиная"]},
    {"question":"Как по-английски «прихожая»?","variants":["a floor","a bed","a basement","a hallway"],"answer":["a hallway"]},
    {"question":"Как переводится «a hallway»?","variants":["компьютер","прихожая","шкаф для одежды","картина"],"answer":["прихожая"]},
    {"question":"Как по-английски «холодильник»?","variants":["a living room","an attic","a house","a fridge"],"answer":["a fridge"]},
    {"question":"Как переводится «a fridge»?","variants":["спальня","книжный шкаф","холодильник","занавеска"],"answer":["холодильник"]},
    {"question":"Как по-английски «телевизор»?","variants":["a bed","a door","a TV","a blanket"],"answer":["a TV"]},
    {"question":"Как переводится «a TV»?","variants":["кровать","телевизор","шкаф для одежды","телефон"],"answer":["телевизор"]},
    {"question":"Как по-английски «компьютер»?","variants":["a living room","a blanket","a computer","a shelf"],"answer":["a computer"]},
    {"question":"Как переводится «a computer»?","variants":["диван","душ","компьютер","кресло"],"answer":["компьютер"]},
    {"question":"Как по-английски «книжный шкаф»?","variants":["a bookcase","a kitchen","a wall","a garden"],"answer":["a bookcase"]},
    {"question":"Как переводится «a bookcase»?","variants":["стул","зеркало","картина","книжный шкаф"],"answer":["книжный шкаф"]},
    {"question":"Как по-английски «шкаф для одежды»?","variants":["a wardrobe","a bookcase","an attic","a table"],"answer":["a wardrobe"]},
    {"question":"Как переводится «a wardrobe»?","variants":["полка","стул","шкаф для одежды","дверной звонок"],"answer":["шкаф для одежды"]},
    {"question":"Как по-английски «зеркало»?","variants":["a mirror","an attic","a floor","a TV"],"answer":["a mirror"]},
    {"question":"Как переводится «a mirror»?","variants":["душ","пол","зеркало","дом"],"answer":["зеркало"]},
    {"question":"Как по-английски «кресло»?","variants":["a floor","a radio","a bookcase","an armchair"],"answer":["an armchair"]},
    {"question":"Как переводится «an armchair»?","variants":["кресло","зеркало","компьютер","комната"],"answer":["кресло"]},
    {"question":"Как по-английски «ковёр»?","variants":["a doorbell","a living room","an armchair","a carpet"],"answer":["a carpet"]},
    {"question":"Как переводится «a carpet»?","variants":["картина","диван","ковёр","лампа"],"answer":["ковёр"]},
    {"question":"Как по-английски «картина»?","variants":["a table","a basement","a fridge","a picture"],"answer":["a picture"]},
    {"question":"Как переводится «a picture»?","variants":["чердак","телефон","картина","гараж"],"answer":["картина"]},
    {"question":"Как по-английски «часы»?","variants":["a clock","a wall","a bookcase","a telephone"],"answer":["a clock"]},
    {"question":"Как переводится «a clock»?","variants":["палас","картина","часы","дверь"],"answer":["часы"]},
    {"question":"Как по-английски «радио»?","variants":["a curtain","a roof","an attic","a radio"],"answer":["a radio"]},
    {"question":"Как переводится «a radio»?","variants":["душ","кресло","радио","подвал"],"answer":["радио"]},
    {"question":"Как по-английски «телефон»?","variants":["a door","a shelf","a telephone","a table"],"answer":["a telephone"]},
    {"question":"Как переводится «a telephone»?","variants":["телефон","крыша","телевизор","подвал"],"answer":["телефон"]},
    {"question":"Как по-английски «раковина»?","variants":["a door","a sink","a living room","a curtain"],"answer":["a sink"]},
    {"question":"Как переводится «a sink»?","variants":["палас","зеркало","раковина","картина"],"answer":["раковина"]},
    {"question":"Как по-английски «душ»?","variants":["a shower","a chair","a picture","a hallway"],"answer":["a shower"]},
    {"question":"Как переводится «a shower»?","variants":["дверной звонок","спальня","стул","душ"],"answer":["душ"]},
    {"question":"Как по-английски «гараж»?","variants":["a wall","a sink","a window","a garage"],"answer":["a garage"]},
    {"question":"Как переводится «a garage»?","variants":["кресло","картина","подвал","гараж"],"answer":["гараж"]},
    {"question":"Как по-английски «балкон»?","variants":["a staircase","a balcony","a radio","a wall"],"answer":["a balcony"]},
    {"question":"Как переводится «a balcony»?","variants":["телевизор","гараж","балкон","палас"],"answer":["балкон"]},
    {"question":"Как по-английски «лестница»?","variants":["a wardrobe","a balcony","a room","a staircase"],"answer":["a staircase"]},
    {"question":"Как переводится «a staircase»?","variants":["полка","зеркало","лестница","кровать"],"answer":["лестница"]},
    {"question":"Как по-английски «занавеска»?","variants":["a curtain","a bathroom","a wall","a fridge"],"answer":["a curtain"]},
    {"question":"Как переводится «a curtain»?","variants":["шкаф для одежды","радио","занавеска","дверной звонок"],"answer":["занавеска"]},
    {"question":"Как по-английски «дверной звонок»?","variants":["a doorbell","a floor","a radio","a fridge"],"answer":["a doorbell"]},
    {"question":"Как переводится «a doorbell»?","variants":["дверной звонок","ковёр","лампа","диван"],"answer":["дверной звонок"]},
    {"question":"Как по-английски «подушка»?","variants":["a chair","a balcony","a pillow","a staircase"],"answer":["a pillow"]},
    {"question":"Как переводится «a pillow»?","variants":["подушка","диван","лестница","зеркало"],"answer":["подушка"]},
    {"question":"Как по-английски «одеяло»?","variants":["a doorbell","a computer","a blanket","a window"],"answer":["a blanket"]},
    {"question":"Как переводится «a blanket»?","variants":["зеркало","часы","одеяло","душ"],"answer":["одеяло"]},
    {"question":"Как по-английски «полка»?","variants":["a doorbell","a table","a shelf","a wall"],"answer":["a shelf"]},
    {"question":"Как переводится «a shelf»?","variants":["кресло","дверь","полка","стол"],"answer":["полка"]},
    {"question":"Как по-английски «палас»?","variants":["a doorbell","an attic","a carpet","a pillow"],"answer":["a carpet"]},
    {"question":"Как по-английски «чердак»?","variants":["an attic","a carpet","a roof","a window"],"answer":["an attic"]},
    {"question":"Как переводится «an attic»?","variants":["комната","окно","сад","чердак"],"answer":["чердак"]},
    {"question":"Как по-английски «подвал»?","variants":["a sink","a basement","a door","a TV"],"answer":["a basement"]},
    {"question":"Как переводится «a basement»?","variants":["подвал","диван","стул","компьютер"],"answer":["подвал"]},
  ]
};
