export default {
  "title": "Дни недели и распорядок дня",
  "questions": [
    {"question":"Как по-английски «понедельник»?","variants":["Sunday","Thursday","Friday","Monday"],"answer":["Monday"]},
    {"question":"Как переводится «Monday»?","variants":["вторник","четверг","воскресенье","понедельник"],"answer":["понедельник"]},
    {"question":"Как по-английски «вторник»?","variants":["Friday","Tuesday","Monday","Wednesday"],"answer":["Tuesday"]},
    {"question":"Как переводится «Tuesday»?","variants":["вторник","среда","понедельник","суббота"],"answer":["вторник"]},
    {"question":"Как по-английски «среда»?","variants":["Monday","Wednesday","Sunday","Saturday"],"answer":["Wednesday"]},
    {"question":"Как переводится «Wednesday»?","variants":["воскресенье","среда","понедельник","пятница"],"answer":["среда"]},
    {"question":"Как по-английски «четверг»?","variants":["Sunday","Tuesday","Thursday","Monday"],"answer":["Thursday"]},
    {"question":"Как переводится «Thursday»?","variants":["четверг","суббота","вторник","пятница"],"answer":["четверг"]},
    {"question":"Как по-английски «пятница»?","variants":["Friday","Sunday","Thursday","Wednesday"],"answer":["Friday"]},
    {"question":"Как переводится «Friday»?","variants":["четверг","пятница","понедельник","среда"],"answer":["пятница"]},
    {"question":"Как по-английски «суббота»?","variants":["Sunday","Tuesday","Saturday","Monday"],"answer":["Saturday"]},
    {"question":"Как переводится «Saturday»?","variants":["четверг","суббота","понедельник","среда"],"answer":["суббота"]},
    {"question":"Как по-английски «воскресенье»?","variants":["Sunday","Tuesday","Wednesday","Friday"],"answer":["Sunday"]},
    {"question":"Как переводится «Sunday»?","variants":["вторник","воскресенье","понедельник","пятница"],"answer":["воскресенье"]},
    {"question":"Как по-английски «вставать»?","variants":["wash","weekend","draw","get up"],"answer":["get up"]},
    {"question":"Как переводится «get up»?","variants":["вечер","принимать душ","готовить","вставать"],"answer":["вставать"]},
    {"question":"Как по-английски «идти в школу»?","variants":["have lunch","go to school","have breakfast","tomorrow"],"answer":["go to school"]},
    {"question":"Как переводится «go to school»?","variants":["идти в школу","принимать душ","приходить домой","вечер"],"answer":["идти в школу"]},
    {"question":"Как по-английски «завтракать»?","variants":["sleep","evening","play football","have breakfast"],"answer":["have breakfast"]},
    {"question":"Как переводится «have breakfast»?","variants":["завтракать","убирать","помогать","завтра"],"answer":["завтракать"]},
    {"question":"Как по-английски «обедать»?","variants":["tomorrow","go to school","have lunch","night"],"answer":["have lunch"]},
    {"question":"Как переводится «have lunch»?","variants":["играть в футбол","обедать","слушать музыку","смотреть телевизор"],"answer":["обедать"]},
    {"question":"Как по-английски «смотреть телевизор»?","variants":["today","watch TV","wash","have breakfast"],"answer":["watch TV"]},
    {"question":"Как переводится «watch TV»?","variants":["завтракать","играть в футбол","смотреть телевизор","утро"],"answer":["смотреть телевизор"]},
    {"question":"Как по-английски «делать уроки»?","variants":["watch TV","do homework","draw","come home"],"answer":["do homework"]},
    {"question":"Как переводится «do homework»?","variants":["обедать","готовить","сегодня","делать уроки"],"answer":["делать уроки"]},
    {"question":"Как по-английски «ложиться спать»?","variants":["morning","go to bed","read","draw"],"answer":["go to bed"]},
    {"question":"Как переводится «go to bed»?","variants":["одеваться","идти гулять","ложиться спать","смотреть телевизор"],"answer":["ложиться спать"]},
    {"question":"Как по-английски «играть в футбол»?","variants":["today","draw","play football","weekend"],"answer":["play football"]},
    {"question":"Как переводится «play football»?","variants":["одеваться","спать","играть в футбол","принимать душ"],"answer":["играть в футбол"]},
    {"question":"Как по-английски «умываться»?","variants":["sleep","morning","clean","wash"],"answer":["wash"]},
    {"question":"Как переводится «wash»?","variants":["смотреть телевизор","ночь","умываться","завтракать"],"answer":["умываться"]},
    {"question":"Как по-английски «читать»?","variants":["morning","read","have a shower","get up"],"answer":["read"]},
    {"question":"Как переводится «read»?","variants":["читать","вставать","одеваться","выходные"],"answer":["читать"]},
    {"question":"Как по-английски «спать»?","variants":["draw","sleep","weekend","watch TV"],"answer":["sleep"]},
    {"question":"Как переводится «sleep»?","variants":["делать уроки","спать","сегодня","идти в школу"],"answer":["спать"]},
    {"question":"Как по-английски «идти домой»?","variants":["go home","brush teeth","cook","morning"],"answer":["go home"]},
    {"question":"Как переводится «go home»?","variants":["идти домой","вставать","идти в школу","ночь"],"answer":["идти домой"]},
    {"question":"Как по-английски «одеваться»?","variants":["get dressed","have lunch","come home","help"],"answer":["get dressed"]},
    {"question":"Как переводится «get dressed»?","variants":["убирать","идти домой","умываться","одеваться"],"answer":["одеваться"]},
    {"question":"Как по-английски «чистить зубы»?","variants":["brush teeth","go to bed","wash","listen to music"],"answer":["brush teeth"]},
    {"question":"Как переводится «brush teeth»?","variants":["одеваться","ложиться спать","чистить зубы","делать уроки"],"answer":["чистить зубы"]},
    {"question":"Как по-английски «принимать душ»?","variants":["clean","go to bed","sleep","have a shower"],"answer":["have a shower"]},
    {"question":"Как переводится «have a shower»?","variants":["слушать музыку","идти домой","принимать душ","смотреть телевизор"],"answer":["принимать душ"]},
    {"question":"Как по-английски «идти гулять»?","variants":["sleep","go for a walk","get up","come home"],"answer":["go for a walk"]},
    {"question":"Как переводится «go for a walk»?","variants":["идти гулять","приходить домой","принимать душ","слушать музыку"],"answer":["идти гулять"]},
    {"question":"Как по-английски «готовить»?","variants":["come home","have breakfast","cook","evening"],"answer":["cook"]},
    {"question":"Как переводится «cook»?","variants":["готовить","смотреть телевизор","ложиться спать","спать"],"answer":["готовить"]},
    {"question":"Как по-английски «убирать»?","variants":["play football","have lunch","go home","clean"],"answer":["clean"]},
    {"question":"Как переводится «clean»?","variants":["утро","идти гулять","одеваться","убирать"],"answer":["убирать"]},
    {"question":"Как по-английски «помогать»?","variants":["sleep","weekend","today","help"],"answer":["help"]},
    {"question":"Как переводится «help»?","variants":["выходные","помогать","одеваться","рисовать"],"answer":["помогать"]},
    {"question":"Как по-английски «слушать музыку»?","variants":["draw","do homework","morning","listen to music"],"answer":["listen to music"]},
    {"question":"Как переводится «listen to music»?","variants":["делать уроки","завтракать","убирать","слушать музыку"],"answer":["слушать музыку"]},
    {"question":"Как по-английски «рисовать»?","variants":["brush teeth","draw","wash","listen to music"],"answer":["draw"]},
    {"question":"Как переводится «draw»?","variants":["чистить зубы","читать","рисовать","спать"],"answer":["рисовать"]},
    {"question":"Как по-английски «приходить домой»?","variants":["come home","watch TV","go to school","go for a walk"],"answer":["come home"]},
    {"question":"Как переводится «come home»?","variants":["приходить домой","делать уроки","помогать","читать"],"answer":["приходить домой"]},
    {"question":"Как по-английски «выходные»?","variants":["get up","listen to music","weekend","clean"],"answer":["weekend"]},
    {"question":"Как переводится «weekend»?","variants":["завтра","утро","выходные","идти домой"],"answer":["выходные"]},
    {"question":"Как по-английски «сегодня»?","variants":["today","get dressed","come home","tomorrow"],"answer":["today"]},
    {"question":"Как переводится «today»?","variants":["спать","делать уроки","играть в футбол","сегодня"],"answer":["сегодня"]},
    {"question":"Как по-английски «завтра»?","variants":["today","have lunch","weekend","tomorrow"],"answer":["tomorrow"]},
    {"question":"Как переводится «tomorrow»?","variants":["рисовать","спать","читать","завтра"],"answer":["завтра"]},
    {"question":"Как по-английски «вечер»?","variants":["go to bed","read","wash","evening"],"answer":["evening"]},
    {"question":"Как переводится «evening»?","variants":["идти в школу","вечер","принимать душ","утро"],"answer":["вечер"]},
    {"question":"Как по-английски «утро»?","variants":["morning","play football","get up","come home"],"answer":["morning"]},
    {"question":"Как переводится «morning»?","variants":["вечер","слушать музыку","утро","идти домой"],"answer":["утро"]},
    {"question":"Как по-английски «ночь»?","variants":["night","have breakfast","play football","sleep"],"answer":["night"]},
    {"question":"Как переводится «night»?","variants":["утро","завтра","делать уроки","ночь"],"answer":["ночь"]},
    {"question":"Выбери число 1 (для времени)","variants":["nine","five","one","four"],"answer":["one"]},
    {"question":"Выбери число 2 (для времени)","variants":["eight","two","eleven","one"],"answer":["two"]},
    {"question":"Выбери число 3 (для времени)","variants":["one","three","five","twelve"],"answer":["three"]},
    {"question":"Выбери число 4 (для времени)","variants":["four","three","six","one"],"answer":["four"]},
    {"question":"Выбери число 5 (для времени)","variants":["six","eleven","five","four"],"answer":["five"]},
    {"question":"Выбери число 6 (для времени)","variants":["eleven","nine","six","two"],"answer":["six"]},
    {"question":"Выбери число 7 (для времени)","variants":["five","seven","six","ten"],"answer":["seven"]},
    {"question":"Выбери число 8 (для времени)","variants":["six","one","three","eight"],"answer":["eight"]},
    {"question":"Выбери число 9 (для времени)","variants":["nine","eight","four","twelve"],"answer":["nine"]},
    {"question":"Выбери число 10 (для времени)","variants":["eleven","ten","eight","five"],"answer":["ten"]},
    {"question":"Выбери число 11 (для времени)","variants":["five","nine","eleven","eight"],"answer":["eleven"]},
    {"question":"Выбери число 12 (для времени)","variants":["four","two","twelve","nine"],"answer":["twelve"]},
  ]
};
