export default {
  "title": "Глагол to be (am/is/are)",
  "questions": [
    {"question":"«I ___ a pupil.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["am"]},
    {"question":"«I ___ my friend.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["am"]},
    {"question":"«I ___ a doctor.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["am"]},
    {"question":"«I ___ happy.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["am"]},
    {"question":"«I ___ nine years old.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["am"]},
    {"question":"«I ___ ten years old.» Выбери правильную форму глагола to be.","variants":["are","am","is"],"answer":["am"]},
    {"question":"«I ___ in the class.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["am"]},
    {"question":"«I ___ at school.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["am"]},
    {"question":"«I ___ from Russia.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["am"]},
    {"question":"«I ___ a teacher.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["am"]},
    {"question":"«I ___ a student.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["am"]},
    {"question":"«I ___ very good.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["am"]},
    {"question":"«I ___ my sister.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["am"]},
    {"question":"«I ___ my brother.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["am"]},
    {"question":"«I ___ our friend.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["am"]},
    {"question":"«I ___ tired.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["am"]},
    {"question":"«I ___ hungry.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["am"]},
    {"question":"«I ___ in the park.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["am"]},
    {"question":"«I ___ at home.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["am"]},
    {"question":"«I ___ small.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["am"]},
    {"question":"«I ___ big and strong.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["am"]},
    {"question":"«I ___ kind.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["am"]},
    {"question":"«I ___ clever and funny.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["am"]},
    {"question":"«I ___ a good boy.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["am"]},
    {"question":"«I ___ a nice girl.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["am"]},
    {"question":"«I ___ ready.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["am"]},
    {"question":"«I ___ on time.» Выбери правильную форму глагола to be.","variants":["are","am","is"],"answer":["am"]},
    {"question":"«I ___ late.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["am"]},
    {"question":"«I ___ my mother.» Выбери правильную форму глагола to be.","variants":["are","am","is"],"answer":["am"]},
    {"question":"«I ___ my father.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["am"]},
    {"question":"«He ___ a pupil.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["is"]},
    {"question":"«He ___ my friend.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«He ___ a doctor.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«He ___ happy.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«He ___ nine years old.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«He ___ ten years old.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["is"]},
    {"question":"«He ___ in the class.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«He ___ at school.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["is"]},
    {"question":"«He ___ from Russia.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«He ___ a teacher.» Выбери правильную форму глагола to be.","variants":["are","am","is"],"answer":["is"]},
    {"question":"«He ___ a student.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["is"]},
    {"question":"«He ___ very good.» Выбери правильную форму глагола to be.","variants":["are","am","is"],"answer":["is"]},
    {"question":"«He ___ my sister.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«He ___ my brother.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«He ___ our friend.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["is"]},
    {"question":"«He ___ tired.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["is"]},
    {"question":"«He ___ hungry.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«He ___ in the park.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«He ___ at home.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["is"]},
    {"question":"«He ___ small.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["is"]},
    {"question":"«He ___ big and strong.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«He ___ kind.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["is"]},
    {"question":"«He ___ clever and funny.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["is"]},
    {"question":"«He ___ a good boy.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["is"]},
    {"question":"«He ___ a nice girl.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«He ___ ready.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["is"]},
    {"question":"«He ___ on time.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«He ___ late.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«He ___ my mother.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«He ___ my father.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["is"]},
    {"question":"«She ___ a pupil.» Выбери правильную форму глагола to be.","variants":["are","am","is"],"answer":["is"]},
    {"question":"«She ___ my friend.» Выбери правильную форму глагола to be.","variants":["are","am","is"],"answer":["is"]},
    {"question":"«She ___ a doctor.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["is"]},
    {"question":"«She ___ happy.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«She ___ nine years old.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["is"]},
    {"question":"«She ___ ten years old.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["is"]},
    {"question":"«She ___ in the class.» Выбери правильную форму глагола to be.","variants":["are","am","is"],"answer":["is"]},
    {"question":"«She ___ at school.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«She ___ from Russia.» Выбери правильную форму глагола to be.","variants":["are","am","is"],"answer":["is"]},
    {"question":"«She ___ a teacher.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["is"]},
    {"question":"«She ___ a student.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["is"]},
    {"question":"«She ___ very good.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«She ___ my sister.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«She ___ my brother.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["is"]},
    {"question":"«She ___ our friend.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«She ___ tired.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«She ___ hungry.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«She ___ in the park.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«She ___ at home.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["is"]},
    {"question":"«She ___ small.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«She ___ big and strong.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«She ___ kind.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«She ___ clever and funny.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«She ___ a good boy.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["is"]},
    {"question":"«She ___ a nice girl.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«She ___ ready.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["is"]},
    {"question":"«She ___ on time.» Выбери правильную форму глагола to be.","variants":["are","am","is"],"answer":["is"]},
    {"question":"«She ___ late.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["is"]},
    {"question":"«She ___ my mother.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["is"]},
    {"question":"«She ___ my father.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["is"]},
    {"question":"«It ___ a pupil.» Выбери правильную форму глагола to be.","variants":["am","are","is"],"answer":["is"]},
    {"question":"«It ___ my friend.» Выбери правильную форму глагола to be.","variants":["is","are","am"],"answer":["is"]},
    {"question":"«It ___ a doctor.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["is"]},
    {"question":"«It ___ happy.» Выбери правильную форму глагола to be.","variants":["are","am","is"],"answer":["is"]},
    {"question":"«It ___ nine years old.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["is"]},
    {"question":"«It ___ ten years old.» Выбери правильную форму глагола to be.","variants":["are","is","am"],"answer":["is"]},
    {"question":"«It ___ in the class.» Выбери правильную форму глагола to be.","variants":["are","am","is"],"answer":["is"]},
    {"question":"«It ___ at school.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["is"]},
    {"question":"«It ___ from Russia.» Выбери правильную форму глагола to be.","variants":["am","is","are"],"answer":["is"]},
    {"question":"«It ___ a teacher.» Выбери правильную форму глагола to be.","variants":["is","am","are"],"answer":["is"]},
  ]
};
