services:
  nginx:
    image: nginx:latest
    container_name: web_server
    ports:
      - "84:80"
    volumes:
      # Привязка локальной папки ./html к стандартной папке nginx в контейнере
      - ./dist:/usr/share/nginx/html:ro
    restart: unless-stopped