export default{
  "title": "Spotlight 2. Starter Module: My Family & Colors",
  "questions": [
    { "question": "Переведи: 'Mummy'", "variants": ["Мама", "Папа", "Бабушка", "Сестра"], "answer": ["Мама"] },
    { "question": "Как по-английски 'Папа'?", "variants": ["Mummy", "Daddy", "Grandpa", "Brother"], "answer": ["Daddy"] },
    { "question": "Переведи: 'Grandma'", "variants": ["Дедушка", "Мама", "Бабушка", "Тетя"], "answer": ["Бабушка"] },
    { "question": "Как по-английски 'Дедушка'?", "variants": ["Grandma", "Grandpa", "Daddy", "Father"], "answer": ["Grandpa"] },
    { "question": "Что такое 'Family'?", "variants": ["Друзья", "Семья", "Школа", "Класс"], "answer": ["Семья"] },
    { "question": "Переведи цвет: 'Red'", "variants": ["Зеленый", "Красный", "Синий", "Желтый"], "answer": ["Красный"] },
    { "question": "Как по-английски 'Синий'?", "variants": ["Black", "Blue", "Brown", "White"], "answer": ["Blue"] },
    { "question": "Цвет 'Green' — это...", "variants": ["Красный", "Зеленый", "Оранжевый"], "answer": ["Зеленый"] },
    { "question": "Цвет 'Yellow' — это...", "variants": ["Белый", "Желтый", "Розовый"], "answer": ["Желтый"] },
    { "question": "Как переводится 'White'?", "variants": ["Черный", "Серый", "Белый"], "answer": ["Белый"] },
    { "question": "Цвет 'Black' — это...", "variants": ["Черный", "Коричневый", "Синий"], "answer": ["Черный"] },
    { "question": "Переведи: 'Hello!'", "variants": ["Пока!", "Привет!", "Спасибо!"], "answer": ["Привет!"] },
    { "question": "Как по-английски 'До свидания'?", "variants": ["Hello", "Goodbye", "Please"], "answer": ["Goodbye"] },
    { "question": "Что значит вопрос: 'What's your name?'", "variants": ["Как дела?", "Как тебя зовут?", "Сколько тебе лет?"], "answer": ["Как тебя зовут?"] },
    { "question": "Как ответить на вопрос 'What's your name?'", "variants": ["I am fine", "My name is Lulu", "I am 7"], "answer": ["My name is Lulu"] },
    { "question": "Переведи: 'Brother'", "variants": ["Сестра", "Брат", "Друг"], "answer": ["Брат"] },
    { "question": "Как по-английски 'Сестра'?", "variants": ["Sister", "Brother", "Mother"], "answer": ["Sister"] },
    { "question": "Цвет 'Pink' — это...", "variants": ["Красный", "Розовый", "Фиолетовый"], "answer": ["Розовый"] },
    { "question": "Цвет 'Orange' — это...", "variants": ["Оранжевый", "Желтый", "Коричневый"], "answer": ["Оранжевый"] },
    { "question": "Переведи: 'Brown'", "variants": ["Черный", "Коричневый", "Серый"], "answer": ["Коричневый"] },
    { "question": "Как сказать 'Моя мама'?", "variants": ["My Mummy", "Your Mummy", "His Mummy"], "answer": ["My Mummy"] },
    { "question": "Как сказать 'Твой папа'?", "variants": ["My Daddy", "Your Daddy", "Her Daddy"], "answer": ["Your Daddy"] },
    { "question": "Что значит 'I am...'?", "variants": ["Я есть... (Меня зовут...)", "Ты есть...", "Он есть..."], "answer": ["Я есть... (Меня зовут...)"] },
    { "question": "Переведи: 'This is my family'", "variants": ["Это моя семья", "Я люблю семью", "Где моя семья?"], "answer": ["Это моя семья"] },
    { "question": "Как по-английски 'Рад встрече' (приятно познакомиться)?", "variants": ["Hello", "Nice to meet you", "Goodbye"], "answer": ["Nice to meet you"] },
    { "question": "Что такое 'Chimp'?", "variants": ["Кошка", "Собака", "Обезьяна (шимпанзе)"], "answer": ["Обезьяна (шимпанзе)"] },
    { "question": "Как переводится 'Punch and Judy'?", "variants": ["Имена героев (кукол)", "Еда", "Цвета"], "answer": ["Имена героев (кукол)"] },
    { "question": "Буква 'A' звучит как...", "variants": ["/æ/ (э)", "/b/ (б)", "/k/ (к)"], "answer": ["/æ/ (э)"] },
    { "question": "С какого слова начинается знакомство в Spotlight?", "variants": ["Hello!", "Apple", "Ant"], "answer": ["Hello!"] },
    { "question": "Переведи: 'A red apple'", "variants": ["Зеленое яблоко", "Красное яблоко", "Сладкое яблоко"], "answer": ["Красное яблоко"] },
    { "question": "Как сказать 'Зеленый муравей'?", "variants": ["Red ant", "Green ant", "Black ant"], "answer": ["Green ant"] },
    { "question": "Что такое 'Cat'?", "variants": ["Кот", "Собака", "Кролик"], "answer": ["Кот"] },
    { "question": "Как по-английски 'Кровать'?", "variants": ["Bed", "Bad", "Red"], "answer": ["Bed"] },
    { "question": "Переведи: 'Blue flag'", "variants": ["Синий флаг", "Красный флаг", "Белый флаг"], "answer": ["Синий флаг"] },
    { "question": "Что такое 'Egg'?", "variants": ["Яблоко", "Яйцо", "Апельсин"], "answer": ["Яйцо"] },
    { "question": "Как по-английски 'Стакан'?", "variants": ["Glass", "Cup", "Box"], "answer": ["Glass"] },
    { "question": "Переведи: 'Ink'", "variants": ["Краска", "Чернила", "Ручка"], "answer": ["Чернила"] },
    { "question": "Что такое 'Kite'?", "variants": ["Кот", "Воздушный змей", "Ключ"], "answer": ["Воздушный змей"] },
    { "question": "Как по-английски 'Лимон'?", "variants": ["Lemon", "Melon", "Apple"], "answer": ["Lemon"] },
    { "question": "Переведи: 'Melon'", "variants": ["Арбуз", "Дыня", "Тыква"], "answer": ["Дыня"] },
    { "question": "Что такое 'Nest'?", "variants": ["Нос", "Гнездо", "Сетка"], "answer": ["Гнездо"] },
    { "question": "Как по-английски 'Апельсин'?", "variants": ["Apple", "Orange", "Banana"], "answer": ["Orange"] },
    { "question": "Переведи: 'Queen'", "variants": ["Король", "Королева", "Принцесса"], "answer": ["Королева"] },
    { "question": "Что такое 'Rabbit'?", "variants": ["Крыса", "Кролик", "Заяц"], "answer": ["Кролик"] },
    { "question": "Как по-английски 'Змея'?", "variants": ["Snake", "Snail", "Spider"], "answer": ["Snake"] },
    { "question": "Переведи: 'Vest'", "variants": ["Жилет", "Куртка", "Майка"], "answer": ["Жилет"] },
    { "question": "Что такое 'Window'?", "variants": ["Дверь", "Окно", "Стена"], "answer": ["Окно"] },
    { "question": "Как по-английски 'Яхта'?", "variants": ["Yacht", "Ship", "Boat"], "answer": ["Yacht"] },
    { "question": "Переведи: 'Zebra'", "variants": ["Лошадь", "Зебра", "Тигр"], "answer": ["Зебра"] },
    { "question": "Как сказать 'Черная кошка'?", "variants": ["A black cat", "A white cat", "A black dog"], "answer": ["A black cat"] },
    { "question": "Переведи: 'Yellow sun'", "variants": ["Желтое солнце", "Красное солнце", "Желтая луна"], "answer": ["Желтое солнце"] },
    { "question": "Что значит 'Listen'?", "variants": ["Смотри", "Слушай", "Читай"], "answer": ["Слушай"] },
    { "question": "Что значит 'Repeat'?", "variants": ["Повторяй", "Пиши", "Рисуй"], "answer": ["Повторяй"] },
    { "question": "Как переводится 'Sing'?", "variants": ["Танцевать", "Петь", "Играть"], "answer": ["Петь"] },
    { "question": "Что такое 'Point to...'?", "variants": ["Покажи на...", "Возьми...", "Открой..."], "answer": ["Покажи на..."] },
    { "question": "Как поздороваться с учителем?", "variants": ["Hello!", "Goodbye!", "Thank you!"], "answer": ["Hello!"] },
    { "question": "Как сказать 'Это мама'?", "variants": ["This is Mummy", "I am Mummy", "Goodbye Mummy"], "answer": ["This is Mummy"] },
    { "question": "Выбери правильный перевод: 'Purple'", "variants": ["Розовый", "Фиолетовый", "Серый"], "answer": ["Фиолетовый"] },
    { "question": "Как переводится 'Grey'?", "variants": ["Зеленый", "Серый", "Голубой"], "answer": ["Серый"] },
    { "question": "Как по-английски 'Цвета'?", "variants": ["Numbers", "Colors", "Letters"], "answer": ["Colors"] },
    { "question": "Закончи фразу: 'My name ... Larry'", "variants": ["is", "am", "are"], "answer": ["is"] },
    { "question": "Как сказать 'Мне 7 лет'?", "variants": ["I am seven", "I have seven", "My seven"], "answer": ["I am seven"] },
    { "question": "Переведи: 'A green box'", "variants": ["Зеленая коробка", "Синяя коробка", "Зеленая книга"], "answer": ["Зеленая коробка"] },
    { "question": "Что такое 'Dog'?", "variants": ["Кот", "Собака", "Утка"], "answer": ["Собака"] },
    { "question": "Как по-английски 'Мальчик'?", "variants": ["Girl", "Boy", "Child"], "answer": ["Boy"] },
    { "question": "Как по-английски 'Девочка'?", "variants": ["Boy", "Girl", "Sister"], "answer": ["Girl"] },
    { "question": "Переведи: 'Stand up!'", "variants": ["Сядьте!", "Встаньте!", "Идите!"], "answer": ["Встаньте!"] },
    { "question": "Переведи: 'Sit down!'", "variants": ["Встаньте!", "Сядьте!", "Слушайте!"], "answer": ["Сядьте!"] },
    { "question": "Что значит 'Open your book'?", "variants": ["Закрой книгу", "Открой книгу", "Дай книгу"], "answer": ["Открой книгу"] },
    { "question": "Что значит 'Close your book'?", "variants": ["Открой книгу", "Закрой книгу", "Читай книгу"], "answer": ["Закрой книгу"] },
    { "question": "Как по-английски 'Один'?", "variants": ["One", "Two", "Three"], "answer": ["One"] },
    { "question": "Как по-английски 'Два'?", "variants": ["One", "Two", "Four"], "answer": ["Two"] },
    { "question": "Как по-английски 'Три'?", "variants": ["Two", "Three", "Five"], "answer": ["Three"] },
    { "question": "Как по-английски 'Четыре'?", "variants": ["Three", "Four", "Five"], "answer": ["Four"] },
    { "question": "Как по-английски 'Пять'?", "variants": ["Four", "Five", "Six"], "answer": ["Five"] },
    { "question": "Как по-английски 'Шесть'?", "variants": ["Five", "Six", "Seven"], "answer": ["Six"] },
    { "question": "Как по-английски 'Семь'?", "variants": ["Six", "Seven", "Eight"], "answer": ["Seven"] },
    { "question": "Как по-английски 'Восемь'?", "variants": ["Seven", "Eight", "Nine"], "answer": ["Eight"] },
    { "question": "Как по-английски 'Девять'?", "variants": ["Eight", "Nine", "Ten"], "answer": ["Nine"] },
    { "question": "Как по-английски 'Десять'?", "variants": ["Nine", "Ten", "One"], "answer": ["Ten"] },
    { "question": "Переведи: 'I love my family'", "variants": ["Я вижу семью", "Я люблю свою семью", "Это моя семья"], "answer": ["Я люблю свою семью"] },
    { "question": "Как спросить 'Кто это?'", "variants": ["Who's this?", "What's this?", "Where's this?"], "answer": ["Who's this?"] },
    { "question": "Как переводится 'Teacher'?", "variants": ["Ученик", "Учитель", "Врач"], "answer": ["Учитель"] },
    { "question": "Что такое 'School'?", "variants": ["Школа", "Дом", "Парк"], "answer": ["Школа"] },
    { "question": "Как сказать 'Красный карандаш'?", "variants": ["Red pencil", "Blue pencil", "Red pen"], "answer": ["Red pencil"] },
    { "question": "Переведи: 'Clap your hands!'", "variants": ["Топни ногой!", "Хлопай в ладоши!", "Прыгай!"], "answer": ["Хлопай в ладоши!"] },
    { "question": "Что значит 'Stamp your feet!'?", "variants": ["Хлопай!", "Топай ногами!", "Танцуй!"], "answer": ["Топай ногами!"] },
    { "question": "Как по-английски 'Друг'?", "variants": ["Family", "Friend", "Teacher"], "answer": ["Friend"] },
    { "question": "Что значит 'And'?", "variants": ["Но", "И", "Или"], "answer": ["И"] },
    { "question": "Как сказать 'Мама и папа'?", "variants": ["Mummy or Daddy", "Mummy and Daddy", "Mummy with Daddy"], "answer": ["Mummy and Daddy"] },
    { "question": "Переведи: 'Big'", "variants": ["Маленький", "Большой", "Длинный"], "answer": ["Большой"] },
    { "question": "Переведи: 'Little'", "variants": ["Маленький", "Большой", "Высокий"], "answer": ["Маленький"] },
    { "question": "Что такое 'Nanny Rose'?", "variants": ["Имя сестры", "Имя няни", "Имя мамы"], "answer": ["Имя няни"] },
    { "question": "Как зовут обезьянку в учебнике?", "variants": ["Larry", "Chuckles", "Lulu"], "answer": ["Chuckles"] },
    { "question": "Как зовут мальчика, главного героя?", "variants": ["Larry", "Paco", "Chuckle"], "answer": ["Larry"] },
    { "question": "Как зовут девочку, главную героиню?", "variants": ["Lulu", "Maya", "Rose"], "answer": ["Lulu"] },
    { "question": "Переведи: 'Look at me!'", "variants": ["Слушай меня!", "Посмотри на меня!", "Повторяй за мной!"], "answer": ["Посмотри на меня!"] },
    { "question": "Как по-английски 'Это...' (для неодушевленных)?", "variants": ["She is", "He is", "It is"], "answer": ["It is"] },
    { "question": "Что значит 'Nice!'?", "variants": ["Плохо", "Мило/Хорошо", "Зло"], "answer": ["Мило/Хорошо"] },
    { "question": "Как сказать 'Я — Лулу'?", "variants": ["I am Lulu", "My Lulu", "Is Lulu"], "answer": ["I am Lulu"] }
  ]
}
