export default {
  "title": "Spotlight 2. Module 1: My Home!",
  "questions": [
    { "question": "Переведи слово: 'House'", "variants": ["Сад", "Дом", "Кухня", "Комната"], "answer": ["Дом"] },
    { "question": "Как по-английски 'Кухня'?", "variants": ["Bedroom", "Kitchen", "Bathroom", "Garden"], "answer": ["Kitchen"] },
    { "question": "Переведи слово: 'Bedroom'", "variants": ["Спальня", "Ванная", "Гостиная", "Гараж"], "answer": ["Спальня"] },
    { "question": "Где живет рыбка? (fish)", "variants": ["In the bedroom", "In the bathroom", "In the garden"], "answer": ["In the bathroom"] },
    { "question": "Как по-английски 'Сад'?", "variants": ["Park", "Kitchen", "Garden", "Yard"], "answer": ["Garden"] },
    { "question": "Переведи слово: 'Chair'", "variants": ["Стол", "Стул", "Кровать", "Радио"], "answer": ["Стул"] },
    { "question": "Как по-английски 'Стол'?", "variants": ["Table", "Chair", "Bed", "Shelf"], "answer": ["Table"] },
    { "question": "Что такое 'Radio'?", "variants": ["Телевизор", "Радио", "Телефон", "Компьютер"], "answer": ["Радио"] },
    { "question": "Как переводится 'Bed'?", "variants": ["Стул", "Кровать", "Стол", "Окно"], "answer": ["Кровать"] },
    { "question": "Выбери правильный перевод: 'Blue chair'", "variants": ["Красный стул", "Синий стул", "Зеленый стол"], "answer": ["Синий стул"] },
    { "question": "Как сказать 'В саду'?", "variants": ["On the garden", "At the garden", "In the garden"], "answer": ["In the garden"] },
    { "question": "Переведи: 'Yellow table'", "variants": ["Желтый стол", "Зеленый стол", "Белый стул"], "answer": ["Желтый стол"] },
    { "question": "Что такое 'Bathroom'?", "variants": ["Спальня", "Ванная комната", "Кухня"], "answer": ["Ванная комната"] },
    { "question": "Как по-английски 'Дерево'?", "variants": ["Tree", "Flower", "Plant", "Apple"], "answer": ["Tree"] },
    { "question": "Переведи фразу: 'A red bed'", "variants": ["Красная кровать", "Рыжий кот", "Красная коробка"], "answer": ["Красная кровать"] },
    { "question": "Где мы спим?", "variants": ["In the kitchen", "In the garden", "In the bedroom"], "answer": ["In the bedroom"] },
    { "question": "Как спросить: 'Где Лулу?'", "variants": ["Who is Lulu?", "Where's Lulu?", "What's Lulu?"], "answer": ["Where's Lulu?"] },
    { "question": "Закончи ответ: 'Where's Chuckles?' — '... in the kitchen.'", "variants": ["He's", "It's", "She's"], "answer": ["He's"] },
    { "question": "Как переводится 'Tree house'?", "variants": ["Дом у дерева", "Дом на дереве", "Деревянный дом"], "answer": ["Дом на дереве"] },
    { "question": "Выбери лишнее слово:", "variants": ["Kitchen", "Bedroom", "Table"], "answer": ["Table"] },
    { "question": "Что такое 'Black chair'?", "variants": ["Белый стул", "Черный стул", "Черный стол"], "answer": ["Черный стул"] },
    { "question": "Как по-английски 'Белый'?", "variants": ["White", "Yellow", "Brown", "Black"], "answer": ["White"] },
    { "question": "Переведи: 'Brown bed'", "variants": ["Коричневая кровать", "Черная кровать", "Белая кровать"], "answer": ["Коричневая кровать"] },
    { "question": "Как сказать 'Где папа?'", "variants": ["Where's Daddy?", "Where's Mummy?", "Who's Daddy?"], "answer": ["Where's Daddy?"] },
    { "question": "Что такое 'Living room'?", "variants": ["Кухня", "Зал (гостиная)", "Прихожая"], "answer": ["Зал (гостиная)"] },
    { "question": "Как переводится 'Window'?", "variants": ["Дверь", "Окно", "Стена", "Пол"], "answer": ["Окно"] },
    { "question": "Цвет 'Green' — это...", "variants": ["Красный", "Зеленый", "Голубой"], "answer": ["Зеленый"] },
    { "question": "Закончи фразу: 'Where is Grandma?' — 'She's in the...'", "variants": ["Garden", "Chair", "Table"], "answer": ["Garden"] },
    { "question": "Как по-английски 'Мама'?", "variants": ["Mummy", "Daddy", "Grandma"], "answer": ["Mummy"] },
    { "question": "Как переводится 'Door'?", "variants": ["Окно", "Дверь", "Стул"], "answer": ["Дверь"] },
    { "question": "Слово 'Fridge' означает...", "variants": ["Плита", "Микроволновка", "Холодильник"], "answer": ["Холодильник"] },
    { "question": "Как сказать 'В кухне'?", "variants": ["In the kitchen", "On the kitchen", "Under the kitchen"], "answer": ["In the kitchen"] },
    { "question": "Переведи: 'Green tree'", "variants": ["Зеленая трава", "Зеленое дерево", "Большое дерево"], "answer": ["Зеленое дерево"] },
    { "question": "Как спросить: 'Это стул?'", "variants": ["Is it a chair?", "It is a chair?", "Is this chair?"], "answer": ["Is it a chair?"] },
    { "question": "Правильный ответ на вопрос: 'Is it a table?'", "variants": ["Yes, it is", "Yes, I am", "No, it's a chair"], "answer": ["Yes, it is"] },
    { "question": "Что такое 'Shelf'?", "variants": ["Шкаф", "Полка", "Тумбочка"], "answer": ["Полка"] },
    { "question": "Как переводится 'Lamp'?", "variants": ["Лампа", "Люстра", "Свет"], "answer": ["Лампа"] },
    { "question": "Выбери слово, обозначающее цвет:", "variants": ["Garden", "Orange", "House"], "answer": ["Orange"] },
    { "question": "Как по-английски 'Дедушка'?", "variants": ["Grandpa", "Grandma", "Daddy"], "answer": ["Grandpa"] },
    { "question": "Переведи: 'Red house'", "variants": ["Красный дом", "Розовый дом", "Красивый дом"], "answer": ["Красный дом"] },
    { "question": "Где стоит плита? (cooker)", "variants": ["In the bedroom", "In the kitchen", "In the garden"], "answer": ["In the kitchen"] },
    { "question": "Как переводится 'Pink chair'?", "variants": ["Розовый стул", "Фиолетовый стул", "Красный стол"], "answer": ["Розовый стул"] },
    { "question": "Что значит 'Look!'?", "variants": ["Слушай!", "Смотри!", "Читай!"], "answer": ["Смотри!"] },
    { "question": "Как по-английски 'Маленький'?", "variants": ["Big", "Small", "Tall"], "answer": ["Small"] },
    { "question": "Переведи: 'A big house'", "variants": ["Маленький дом", "Большой дом", "Старый дом"], "answer": ["Большой дом"] },
    { "question": "Как сказать 'Где дедушка?'", "variants": ["Where's Grandpa?", "Where's Grandma?", "Who's Grandpa?"], "answer": ["Where's Grandpa?"] },
    { "question": "Слово 'Cupboard' — это...", "variants": ["Чашка", "Шкаф для посуды", "Стол"], "answer": ["Шкаф для посуды"] },
    { "question": "Как по-английски 'Серый'?", "variants": ["Grey", "Green", "Great"], "answer": ["Grey"] },
    { "question": "Что такое 'Flower'?", "variants": ["Дерево", "Цветок", "Трава"], "answer": ["Цветок"] },
    { "question": "Переведи фразу: 'My home'", "variants": ["Твой дом", "Мой дом", "Наш дом"], "answer": ["Мой дом"] },
    { "question": "Выбери правильное написание слова 'Кухня':", "variants": ["Kichen", "Kitchen", "Kitchin"], "answer": ["Kitchen"] },
    { "question": "Как сказать 'В доме'?", "variants": ["In the house", "On the house", "Under the house"], "answer": ["In the house"] },
    { "question": "Переведи: 'A blue bed'", "variants": ["Синяя кровать", "Голубая кровать", "Оба варианта"], "answer": ["Оба варианта"] },
    { "question": "Что значит 'Lovely'?", "variants": ["Грустный", "Чудесный/прекрасный", "Скучный"], "answer": ["Чудесный/прекрасный"] },
    { "question": "Как по-английски 'Где...?'", "variants": ["What", "Where", "Who"], "answer": ["Where"] },
    { "question": "Цвет 'Purple' — это...", "variants": ["Розовый", "Фиолетовый", "Серый"], "answer": ["Фиолетовый"] },
    { "question": "Как переводится 'Chimpanzee'?", "variants": ["Обезьяна", "Шимпанзе", "Мишка"], "answer": ["Шимпанзе"] },
    { "question": "Где обычно находится 'Bath' (ванна)?", "variants": ["In the bathroom", "In the living room", "In the bedroom"], "answer": ["In the bathroom"] },
    { "question": "Как сказать 'Черный стол'?", "variants": ["Black table", "Black chair", "White table"], "answer": ["Black table"] },
    { "question": "Переведи: 'It's a radio'", "variants": ["Это телевизор", "Это радио", "Это телефон"], "answer": ["Это радио"] },
    { "question": "Что такое 'Garden'?", "variants": ["Огород", "Сад", "Лес"], "answer": ["Сад"] },
    { "question": "Как по-английски 'Кровать'?", "variants": ["Bad", "Bed", "Red"], "answer": ["Bed"] },
    { "question": "Выбери лишнее слово (мебель):", "variants": ["Table", "Chair", "Garden"], "answer": ["Garden"] },
    { "question": "Как сказать 'Да' (на вопрос Is it...)?", "variants": ["Yes, it is", "Yes, it isn't", "No, it is"], "answer": ["Yes, it is"] },
    { "question": "Как сказать 'Нет' (на вопрос Is it...)?", "variants": ["No, it is", "No, it isn't", "Yes, it isn't"], "answer": ["No, it isn't"] },
    { "question": "Что такое 'Funny'?", "variants": ["Смешной", "Умный", "Красивый"], "answer": ["Смешной"] },
    { "question": "Как переводится 'Mirror'?", "variants": ["Окно", "Зеркало", "Картина"], "answer": ["Зеркало"] },
    { "question": "Слово 'Sofa' означает...", "variants": ["Стул", "Диван", "Кровать"], "answer": ["Диван"] },
    { "question": "Как по-английски 'Коричневый'?", "variants": ["Brown", "Black", "Blue"], "answer": ["Brown"] },
    { "question": "Переведи: 'A small table'", "variants": ["Большой стол", "Маленький стул", "Маленький стол"], "answer": ["Маленький стол"] },
    { "question": "Как сказать 'Где мама?'", "variants": ["Where's Mummy?", "Where's Daddy?", "How's Mummy?"], "answer": ["Where's Mummy?"] },
    { "question": "Что такое 'Treehouse'?", "variants": ["Дом из дерева", "Домик на дереве", "Садовый дом"], "answer": ["Домик на дереве"] },
    { "question": "Как по-английски 'Обезьянка Чаклз'?", "variants": ["Chuckles the chimpanzee", "Chuckles the cat", "Chuckles the dog"], "answer": ["Chuckles the chimpanzee"] },
    { "question": "Переведи: 'Is he in the garden?'", "variants": ["Он в саду?", "Она в саду?", "Ты в саду?"], "answer": ["Он в саду?"] },
    { "question": "Ответ: 'No, he isn't. He's in the house.' Переведи:", "variants": ["Нет, он в доме.", "Нет, он в саду.", "Да, он в доме."], "answer": ["Нет, он в доме."] },
    { "question": "Что такое 'Wall'?", "variants": ["Пол", "Стена", "Потолок"], "answer": ["Стена"] },
    { "question": "Как по-английски 'Радио'?", "variants": ["Radio", "TV", "Phone"], "answer": ["Radio"] },
    { "question": "Цвет 'White' — это...", "variants": ["Черный", "Белый", "Серый"], "answer": ["Белый"] },
    { "question": "Как переводится 'Floor'?", "variants": ["Потолок", "Пол", "Окно"], "answer": ["Пол"] },
    { "question": "Закончи фразу: 'My house is...'", "variants": ["Little", "Blue", "Оба варианта верны"], "answer": ["Оба варианта верны"] },
    { "question": "Что такое 'Door'?", "variants": ["Дверь", "Окно", "Стул"], "answer": ["Дверь"] },
    { "question": "Как сказать 'Желтая кровать'?", "variants": ["Yellow bed", "Yellow table", "Green bed"], "answer": ["Yellow bed"] },
    { "question": "Слово 'Nice' означает...", "variants": ["Плохой", "Милый/приятный", "Злой"], "answer": ["Милый/приятный"] },
    { "question": "Переведи: 'Come here!'", "variants": ["Уходи!", "Иди сюда!", "Стой!"], "answer": ["Иди сюда!"] },
    { "question": "Как по-английски 'Бабушка'?", "variants": ["Grandpa", "Grandma", "Mummy"], "answer": ["Grandma"] },
    { "question": "Что такое 'Armchair'?", "variants": ["Стул", "Кресло", "Диван"], "answer": ["Кресло"] },
    { "question": "Переведи: 'A black and white house'", "variants": ["Черно-белый дом", "Черный и красный дом", "Красивый дом"], "answer": ["Черно-белый дом"] },
    { "question": "Как спросить 'Где папа?'", "variants": ["Where's Daddy?", "Where's Mummy?", "What's Daddy?"], "answer": ["Where's Daddy?"] },
    { "question": "Слово 'Bedroom' переводится как...", "variants": ["Кухня", "Спальня", "Ванная"], "answer": ["Спальня"] },
    { "question": "Как сказать 'Это не стол'?", "variants": ["It isn't a table", "It is a table", "Not a table"], "answer": ["It isn't a table"] },
    { "question": "Что такое 'Home'?", "variants": ["Дом (здание)", "Дом (очаг/место)", "Комната"], "answer": ["Дом (очаг/место)"] },
    { "question": "Переведи: 'Yellow chair'", "variants": ["Желтый стул", "Желтая лампа", "Белый стул"], "answer": ["Желтый стул"] },
    { "question": "Как по-английски 'Смотри на меня'?", "variants": ["Look at me", "Listen to me", "Read me"], "answer": ["Look at me"] },
    { "question": "Что такое 'TV'?", "variants": ["Радио", "Телевизор", "Телефон"], "answer": ["Телевизор"] },
    { "question": "Переведи: 'Is it a blue house?'", "variants": ["Это синий дом?", "Это большой дом?", "Это мой дом?"], "answer": ["Это синий дом?"] },
    { "question": "Как по-английски 'Стол'?", "variants": ["Table", "Desk", "Оба варианта"], "answer": ["Оба варианта"] },
    { "question": "Что такое 'Kitchen'?", "variants": ["Кухня", "Зал", "Ванная"], "answer": ["Кухня"] },
    { "question": "Как сказать 'Где ты?'", "variants": ["Where are you?", "Who are you?", "How are you?"], "answer": ["Where are you?"] },
    { "question": "Переведи: 'In the bedroom'", "variants": ["На спальне", "В спальне", "Под спальней"], "answer": ["В спальне"] },
    { "question": "Цвет 'Brown' — это...", "variants": ["Коричневый", "Черный", "Серый"], "answer": ["Коричневый"] }
  ]
}
